- apps/web/modules/wallet.tsx
Just uncommenting some prior code and updating the types. Do we want to the same for staging?
> Enable development on local chain

- apps/web/modules/services/network.ts
> Remove type column from displaying in entities table by default

- apps/web/modules/components/entity/autocomplete/results-list.test.tsx
- apps/web/modules/components/entity/autocomplete/results-list.tsx
The disambiguation priority can be a little confusing, so added some tests to make sure we're doing it correctly.
> feat: add tests for disambiguation code

- apps/web/modules/components/entity-table/entity-table-cell.tsx
- apps/web/modules/components/entity/autocomplete/entity-autocomplete.tsx
- apps/web/modules/components/entity/autocomplete/entity-text-autocomplete.tsx
- apps/web/modules/components/entity/autocomplete/results-list.test.tsx
- apps/web/modules/components/entity/autocomplete/results-list.tsx
- apps/web/modules/components/entity/readable-entity-page.tsx
- apps/web/modules/components/navbar/navbar.tsx
- apps/web/modules/components/triple-table.tsx
- apps/web/modules/design-system/breadcrumb.tsx
- apps/web/modules/design-system/chip.tsx
- apps/web/modules/design-system/tag.tsx
- apps/web/modules/design-system/theme/typography.ts
- apps/web/modules/services/network.ts
- apps/web/modules/types.ts
> Description disambiguation

- docs/schemas.md
Added some basic docs on how data modeling schemas currently work in Geo.
> docs: schemas in Geo

- docs/pages.md
[Rendered doc](https://github.com/geobrowser/geogenesis/blob/e728f2665616721278f80f4210d3b8a9d027ac51/docs/pages.md)
> docs: initial docs on Pages

- packages/subgraph/schema.graphql
- packages/subgraph/src/actions.ts
Here is an example endpoint with these changes deployed: https://thegraph.com/hosted-service/subgraph/mercuricchloride/geo-fulltext-master
For querying and filtering columns you can do something like this:
```
{
triples(where: { 
attribute: "Description",
entity_: {
typeIds_contains: ["f4f48574-71cd-412d-9769-11fc02c8975f"],
}
}, orderBy: stringValue) {
id
stringValue
entityValue {
id
name
}
attribute {
id
name
}
entity {
id
name
}
}
}
```
> adding and removing typeIds

- apps/web/integration/pages/space/[id]/[entityId].test.tsx
- apps/web/modules/components/entity/editable-entity-page.tsx
- apps/web/modules/components/entity/readable-entity-page.tsx
- apps/web/modules/components/entity/types.ts
- apps/web/modules/components/navbar/navbar.tsx
- apps/web/modules/search/autocomplete.ts
- apps/web/modules/services/network-local-mapping.ts
- apps/web/modules/services/network.ts
- apps/web/pages/404.tsx
- apps/web/pages/space/[id].tsx
- apps/web/pages/space/[id]/[entityId].tsx
- apps/web/pages/space/[id]/[entityId]/v2.tsx
- packages/subgraph/schema.graphql
This PR adds the new Referenced by section on Entity Pages. It also simplifies fetching of data on the entity page to use `fetchEntity/fetchEntities` which removes a lot of extra, parallel fetches that were using `fetchTriples`.
This PR also fixes the navigation bug when navigating to entities in another space and correctly navigates to our 404 page when the entity or space at the route do not exist.
---
**Demo here**
[New referenced by section](https://share.cleanshot.com/CdkvWRj7)
[404 redirecting](https://share.cleanshot.com/FbwMzfqq)
> feat: new referenced by section

- apps/web/modules/components/filter/type-dialog.tsx
- apps/web/modules/services/network.ts
We now log additional information for each fetch type, both for runtime errors and for request errors from our dependencies (like the hosted network).
Eventually we want to pipe these errors into some other source for us to consume and be alerted by.
> feat: enhance error logs in network.ts

- apps/web/modules/components/entity/editable-entity-page.tsx
- apps/web/modules/components/entity/entity-page-content-container.tsx
- apps/web/modules/components/entity/entity-page-cover.tsx
- apps/web/modules/components/entity/readable-entity-page.tsx
- apps/web/modules/entity/entity.ts
- apps/web/modules/services/network.ts
- apps/web/pages/space/[id]/[entityId].tsx
- apps/web/pages/space/[id]/create-entity.tsx
- packages/ids/system-ids.ts
This PR adds avatar and cover images to entity pages.
> feat: entity page images

- apps/web/modules/components/history/history-panel.tsx
- apps/web/modules/components/navbar/navbar-breadcrumb.tsx
- apps/web/modules/components/navbar/navbar-link-menu-item.tsx
- apps/web/modules/components/navbar/navbar-link-menu.tsx
- apps/web/modules/components/navbar/navbar.tsx
- apps/web/modules/design-system/breadcrumb.tsx
- apps/web/modules/design-system/icons/chevron-right.tsx
- apps/web/modules/design-system/icons/context.tsx
- apps/web/modules/design-system/menu.tsx
We changed the breadcrumb design to work better with very long space and entity names. It also works better on mobile.
---
**Demo here**
https://share.cleanshot.com/hPLFHhPX
> feat: new navbar breadcrumbs design

- apps/web/modules/components/flow-bar.tsx
This PR makes the flow bar appear in edit mode only.
> fix(flow bar): only show in edit mode

- apps/web/modules/components/editor/blocks/sdk/table.ts
- apps/web/modules/components/editor/blocks/table/table-block-store.tsx
- apps/web/modules/components/editor/blocks/table/table-block.tsx
- apps/web/modules/components/editor/blocks/table/table.tsx
- apps/web/modules/components/triple-input.tsx
- apps/web/modules/design-system/button.tsx
- apps/web/modules/design-system/icon.tsx
- apps/web/modules/design-system/input.tsx
- apps/web/modules/design-system/select.tsx
- apps/web/modules/entity/entity-table-store/entity-table-store.ts
- apps/web/modules/io/data-source/network.ts
- apps/web/modules/io/queries.ts
- apps/web/modules/triple/triple-store.tsx
- apps/web/pages/space/[id].tsx
This initial PR adds filtering tables based on the columns for users locally. A follow-up PR will include storing the filter on the subgraph and applying it for all users.
**Note**: Right now we only support "Contains" as a filter for entity values and string values. Eventually we will support more complex filtering for other value types like number, image, etc.
---
**Demo here**
> feat: local table filtering

- apps/web/modules/components/editor/blocks/table/table-block.tsx
- apps/web/modules/design-system/icon.tsx
- apps/web/modules/design-system/icons/filter-table-with-filters.tsx
This PR adds a new icon to show whether a table has active filters or not.
> feat: filter icon for active filters

- apps/web/integration/pages/space/[id]/entities.test.tsx
- apps/web/modules/components/entity-page/entity-page-metadata-header.tsx
- apps/web/modules/components/entity/editable-entity-header.tsx
- apps/web/modules/components/entity/entity-page-cover.tsx
- apps/web/modules/components/history/history-panel.tsx
- apps/web/modules/design-system/menu.tsx
- apps/web/pages/space/[id].tsx
- apps/web/pages/space/[id]/entities.tsx
This PR adds support for space pages.
> feat: space pages

- apps/web/modules/components/entity/editable-entity-header.tsx
This PR adds a 'New Entity' button when on a space page in edit mode.
> feat: update space pages

- apps/web/modules/components/editor/blocks/table/table-block.tsx
- apps/web/modules/components/table/cell-content.tsx
- apps/web/modules/constants.ts
- apps/web/pages/spaces.tsx
This PR implements the following fixes:
- updates the root space image
- hides unfinished spaces from the spaces gallery
- wraps long table cell text
> fix: ux issues

- apps/web/modules/change/change.ts
- apps/web/modules/components/editor/blocks/table/table-block.tsx
- apps/web/modules/components/review.tsx
This PR adds basic diffs to the review changes UI for the creation, renaming, and deletion of table blocks.
> feat: table block diffs

- apps/web/modules/utils.ts
- apps/web/package.json
- apps/web/pages/_app.tsx
- apps/web/pages/_document.tsx
- apps/web/pages/api/og.tsx
- apps/web/pages/space/[id].tsx
- apps/web/pages/space/[id]/[entityId].tsx
- apps/web/pages/space/[id]/entities.tsx
- apps/web/pages/spaces.tsx
- pnpm-lock.yaml
This PR adds support for dynamic social card images rendered at the edge.
> feat: dynamic social card images

- apps/web/modules/components/editor/blocks/table/table-block.tsx
- apps/web/modules/components/entity/editable-entity-page.tsx
- apps/web/modules/utils.ts
- apps/web/pages/space/[id]/create-entity.tsx
This PR adds a "New Entity" button for table blocks and automatically populates the appropriate `Type`.
> feat: table enhancements

- apps/web/modules/change/change.ts
- apps/web/modules/components/review.tsx
This PR adds support for deleting individual entity actions to the review changes UI.
>  feat: review changes UI improvements

- apps/web/modules/action/actions-store.ts
- apps/web/modules/components/entity/editable-entity-page.tsx
- apps/web/modules/components/review.tsx
- apps/web/modules/design-system/icon.tsx
- apps/web/modules/design-system/icons/dash.tsx
- apps/web/modules/utils.ts
- apps/web/pages/space/[id]/create-entity.tsx
This PR adds support for staging/unstaging attribute changes in the review changes UI.
> feat: review changes UI improvements

- apps/web/modules/change/change.ts
- apps/web/modules/components/review.tsx
- apps/web/modules/entity/entity-store/entity-store.ts
This PR automatically names table blocks with the plural of their type.
> feat: automatically populate new table names

- apps/web/modules/components/entity/editable-entity-header.tsx
- apps/web/modules/components/entity/editable-fields.tsx
- apps/web/package.json
- pnpm-lock.yaml
This PR adds auto resizing for textareas.
> feat: add support for multiline title editing

- apps/web/modules/entity/entity.ts
This PR restores missing type pills from entity pages with multiple types.
> fix: missing type pills

- apps/web/modules/components/review.test.ts
This PR revises the review changes UI tests to expect the new data structure.
> fix: update review changes tests

- packages/ids/system-ids.ts
This PR uses a newly created entity for the shown columns functionality.
> fix: shown columns

- apps/web/modules/components/entity-table/entity-table-cell.tsx
- apps/web/modules/components/entity/editable-fields.tsx
This PR revises images in table blocks to appear in their natural aspect ratio.
> fix: table images

- apps/web/pages/space/[id]/[entityId].tsx
This PR removes the space configuration redirect.
> fix: space page redirect

- apps/web/modules/components/entity/editable-entity-page.tsx
This PR revises the displayed attribute name from "Type" to "Types" on the create entity page.
> fix: new entity types

- apps/web/modules/wallet.tsx
- packages/subgraph/schema.graphql
- packages/subgraph/src/actions.ts
- packages/subgraph/src/add-entry.ts
- packages/subgraph/src/bootstrap.ts
This PR adds the `createdAtBlock` property to proposals and versions.
> feat: upgrade subgraph to support version diffs

- apps/web/pages/space/[id]/[entityId].tsx
This PR restores the space page redirect.
> feat: restore space page redirect

- apps/web/modules/components/editor/blocks/table/table-block-table.tsx
- apps/web/modules/components/entity-table/entity-table-cell.tsx
- apps/web/modules/components/table/cell-content.tsx
- apps/web/modules/components/triple-table.tsx
- apps/web/modules/design-system/chip.tsx
This PR revises the table block styles to increase minimum cell width and number of default lines.
> fix: revise table block styles

- apps/web/modules/utils.ts
- apps/web/pages/api/og.tsx
- apps/web/vercel.json
This PR implements a rewrite to append a file name to open graph images.
> fix: twitter image

- apps/web/modules/change/change.ts
- apps/web/modules/components/review.tsx
This PR adds table filter changes to the review changes UI. It also fixes a bug with intermediate states appearing in the review changes UI.
> feat: review table filter changes

- apps/web/pages/spaces.tsx
This PR hides additional spaces.
> feat: add hidden spaces

- apps/web/modules/components/entity/autocomplete/entity-autocomplete.tsx
- apps/web/modules/components/entity/autocomplete/entity-text-autocomplete.tsx
- apps/web/modules/components/entity/editable-entity-page.tsx
Now when doing Find or Create it adds the relation between the newly created entity and the attribute.
> feat: add relation when creating one that doesn't exist

- apps/web/modules/components/entity-page/entity-page-metadata-header.tsx
- apps/web/modules/components/history/history-panel.tsx
- apps/web/modules/components/space/space-header.tsx
- apps/web/modules/io/data-source/network.ts
- apps/web/modules/io/queries.ts
This PR adds infinite scrolling to the history dropdowns.
> feat: infinite scroll history

- apps/web/modules/auth/use-access-control.ts
This PR always shows admin UI in dev mode.
> feat: dev mode

- apps/web/modules/design-system/icon.tsx
- apps/web/modules/design-system/icons/disconnect-wallet.tsx
- apps/web/modules/design-system/icons/wallet.tsx
- apps/web/modules/wallet.tsx
> feat: new wallet icons

- apps/web/modules/config/config.ts
This reverts commit 783e7d4b031b20ec3b425a0a95ae31f4ff113289.
> fix: use prod subgraph

- apps/web/modules/components/editable-fields/date-field.tsx
The DateField now correctly leaves the placeholder value when first creating the triple
> feat: initial date field ux improvements

- apps/web/modules/components/entity-page/entity-page-metadata-header.tsx
- apps/web/modules/components/space/space-header.tsx
This PR adds the new compare proposals UI to spaces entity/triples table pages.
> feat: compare proposals

- apps/web/modules/action/action.ts
- apps/web/modules/components/compare.tsx
- apps/web/modules/components/editable-fields/date-field.tsx
- apps/web/modules/components/entity-table/editable-entity-table-column-header.tsx
- apps/web/modules/components/entity/editable-entity-page.tsx
- apps/web/modules/components/review.tsx
This PR adds support for date diffs in review changes, compare versions, and compare proposals UI.
It also launches support for the new date type.
> feat: date diffs

- apps/web/modules/io/data-source/network.ts
- apps/web/modules/io/mocks/mock-network.ts
- apps/web/modules/types.ts
- apps/web/pages/spaces.tsx
This PR sorts spaces according to its `createdAtBlock`.
> feat: space sorting

- apps/web/pages/space/[id]/[entityId].tsx
This PR fixes the browser back button behavior when navigating to a subspace.
> fix: subspace redirect bug

- apps/web/modules/components/compare.tsx
- apps/web/modules/components/entity-table/editable-entity-table-column-header.tsx
- apps/web/modules/components/entity/editable-entity-page.tsx
- apps/web/modules/components/review.tsx
This PR adds support for web url diffs in review changes, compare versions, and compare proposals UI.
It also launches support for the new web url type.
> feat: web url diffs

- apps/web/core/io/publish/publish.ts
- apps/web/core/state/actions-store/actions-store.ts
- apps/web/core/types.ts
- apps/web/design-system/icons/tick-small.tsx
- apps/web/design-system/icons/warning.tsx
- apps/web/partials/review/review.tsx
We now surface errors that occur during publishing.
> feat: visible error handling in publish

- apps/web/partials/navbar/navbar-actions.tsx
This PR applies the same styles for both generic avatars and profile images.
> fix: navbar avatar

- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- apps/web/.gitignore
- apps/web/e2e/spaces.spec.ts
- apps/web/package.json
- apps/web/playwright.config.ts
- apps/web/vite.config.js
- pnpm-lock.yaml
This PR adds support for running e2e tests against the web application using playwright.
> feat: e2e test infra

- apps/web/design-system/menu.tsx
This was resulting in not being able to trigger the menu
> fix: remove asChild from menu trigger

- apps/web/core/merged/merged.ts
We may have introduced a bug where the local rows are duplicated if there are remote rows of the same id. It's hard to reproduce, so attempting to revert this for now to see if it still happens.
> fix: revert simplification of rows merging logic

- apps/web/app/space/[id]/[entityId]/template/activity/layout.tsx
- apps/web/app/space/[id]/[entityId]/template/activity/loading.tsx
- apps/web/app/space/[id]/[entityId]/template/activity/page.tsx
- apps/web/app/space/[id]/[entityId]/template/layout.tsx
- apps/web/core/constants.ts
- apps/web/design-system/menu.tsx
- apps/web/design-system/skeleton.tsx
- apps/web/partials/profile/activity-space-filter.tsx
This PR adds capability for filtering a profile's activity by space. It includes support for rendering loading states on the client using suspense in a Next 13-native way.
> feat: activity page space filter

- apps/web/package.json
- pnpm-lock.yaml
Next has made several performance improvements which should make the experience of the app router dev server much faster. Previously we were running into super long fast-refresh and bundling times when navigating.
> feat: upgrade next

- apps/web/package.json
- pnpm-lock.yaml
This reverts commit 91f2304a5b2355e57e7c0f2928e1bbdb75419b58.
> Revert "feat: upgrade next (#457)"

- apps/web/app/space/[id]/component.tsx
When merging the below PR, I accidentally merged the incorrect metadata header for the space page.
https://github.com/geobrowser/geogenesis/pull/459
> fix: incorrect metadata header on space page

- apps/web/core/io/subgraph/fetch-entities.ts
- apps/web/core/merged/merged.ts
This PR adds automatic sorting by name to the fetch entities query.
> fix: add sorting to fetch entities query

- apps/web/core/io/subgraph/fetch-entities.ts
- apps/web/core/merged/merged.ts
This PR restores "contains" to the fetch entities query.
> fix: restore contain query

- apps/web/partials/onboarding/dialog.tsx
This PR adds the new onboarding user flow.
> feat: onboarding

- apps/web/core/state/actions-store/actions-store.ts
This PR revises the IndexedDB persistence implementation to only save unpublished actions.
> fix: persistence

- apps/web/partials/editor/editor.tsx
This PR resolves the performance issue for entities with many content blocks.
> fix: editor performance

- apps/web/app/space/[id]/[entityId]/component.tsx
- apps/web/app/space/[id]/[entityId]/page.tsx
- apps/web/partials/entity-page/editable-entity-header.tsx
This PR resolves the issue of new entities using the entity id as the default name.
> fix: new entity

- apps/web/app/space/[id]/[entityId]/page.tsx
- apps/web/partials/entity-page/entity-page-referenced-by.tsx
This fixes issues with titles and references in new entity creation.
> fix: new entity metadata

- apps/web/app/api/contracts/deploy/make-deploy-effect.ts
- apps/web/app/api/profile/deploy/make-profile-effect.ts
- apps/web/app/api/profile/deploy/route.ts
- apps/web/core/hooks/use-geo-profile.ts
- apps/web/core/hooks/use-onboarding.tsx
- apps/web/core/io/subgraph/fetch-entities.ts
- apps/web/core/utils/utils.ts
- apps/web/partials/onboarding/dialog.tsx
- apps/web/partials/review/flow-bar.tsx
This PR adds logic for retrying individual backend workflow steps during onboarding using exponential backoff.
It's easy to trigger the rate-limiting in our Nodes, so we need to make sure that we can process onboarding without errors.
> feat: exponential backoff retries during onboarding

- apps/web/app/home/component.tsx
- apps/web/app/home/page.tsx
- apps/web/core/providers.tsx
- apps/web/core/state/active-proposal-store/active-proposal-store.tsx
- apps/web/core/state/active-proposal-store/index.tsx
- apps/web/design-system/button.tsx
- apps/web/design-system/icons/time.tsx
- apps/web/partials/active-proposal/active-proposal.tsx
This PR adds the UI for reviewing active proposals.
> feat: review active proposal

- apps/web/app/spaces/page.tsx
- apps/web/design-system/card.tsx
> feat: new space cards design

- apps/web/partials/history/compare.tsx
Not sure if this is the best choice but it fixes a runtime error for now.
> fix: if the profile doesn't have a link default to ''

- apps/web/app/home/page.tsx
Once we have the new governance model this won't matter
> feat: show spaces where user is editor controller

- apps/web/core/state/table-block-store.tsx
For some reason we can end up with an empty "space" filter on "entityOf" in the value of a filter triple. For now we reconstruct the filter string at query time instead of relying on the value of the filter string.
> fix: correctly build filter string before querying

- packages/api/.env.example
- packages/api/.gitignore
- packages/api/Dockerfile
- packages/api/package.json
- packages/api/pnpm-lock.yaml
- packages/api/src/server.ts
- packages/api/tsconfig.json
- packages/substream/package.json
- pnpm-lock.yaml
This PR does not include history. If you want to see history from before this commit, view this repository: https://github.com/makeitrein/geo-postgraphile
> feat: migrate substreams API to our monorepo

- apps/web/design-system/autocomplete/entity-autocomplete.tsx
- apps/web/partials/entity-page/editable-entity-page.tsx
This PR automatically adds the relation value type when creating new entities via find or create.
> fix: add relation value type

- apps/web/partials/onboarding/dialog.tsx
This PR adds support for company spaces in onboarding.
> feat: company onboarding

- apps/web/core/state/actions-store/actions-store.tsx
- apps/web/partials/review/review.tsx
This PR resolves a bug where the review changes UI would remain open even after all changes had been published.
> fix: automatically close review changes UI

- apps/web/app/api/company/deploy/route.ts
- apps/web/app/api/contracts/deploy/route.ts
- apps/web/app/api/errors.ts
- apps/web/app/api/nonprofit/deploy/route.ts
- apps/web/app/api/person/deploy/route.ts
- apps/web/app/api/roles.ts
- apps/web/app/api/space/deploy/make-create-entities-effect.ts
- apps/web/app/api/space/deploy/make-deploy-space-effect.ts
- apps/web/app/api/space/deploy/make-transfer-roles-effect.ts
- apps/web/app/api/space/deploy/route.ts
- apps/web/core/io/publish/contracts.ts
- apps/web/core/types.ts
- apps/web/design-system/dots.tsx
- apps/web/partials/create-space/create-space-dialog.tsx
- apps/web/partials/create-space/create-space-dropdown.tsx
- apps/web/partials/navbar/navbar.tsx
- apps/web/partials/onboarding/dialog.tsx
This PR adds functionality which allows users to create any space ad-hoc.
> feat: create any space dynamically

- apps/web/app/home/page.tsx
- apps/web/core/environment/environment.ts
This will eventually move back to the substream API after we fix a bug where some roles are not getting emitted from the susbtream.
> feat(temp): use the subgraphs for membership requests

- packages/substream/index.ts
- packages/substream/proto/schema.proto
- packages/substream/sink/entries/populate-entries.ts
- packages/substream/sink/populate-roles.ts
- packages/substream/sink/run-stream.ts
- packages/substream/sink/spaces/map-spaces.ts
- packages/substream/sink/utils/get-checksum-address.ts
- packages/substream/src/lib.rs
- packages/substream/src/pb/schema.rs
- packages/substream/substreams.yaml
This PR adds docs to the substream and sink outlining various concepts and _why_ some things are written the way they are right now. Note that substream and sink work for governance is still WIP
> feat(governance): substream/sink docs

- .github/workflows/test.yml
- packages/substream/index.ts
- packages/substream/package.json
- packages/substream/sink/get-stream-configuration.test.ts
- packages/substream/sink/get-stream-configuration.ts
- packages/substream/sink/populate-from-cache.ts
- packages/substream/sink/populate-roles.ts
- packages/substream/tsconfig.json
- pnpm-lock.yaml
This PR improves the configuration model for running the sink and adds tests for generating the config
> feat(sink): improved configuration

- apps/web/core/environment/environment.ts
- packages/membership-subgraph/package.json
- packages/membership-subgraph/src/mapping.ts
This change adds logs for some membership requests and deploys it to a new subgraph.
> fix: membership indexing

- apps/web/partials/blocks/table/table-block-context-menu.tsx
- pnpm-lock.yaml
Dropdown is more of a correct accessibility choice and better maps to how we're using the more actions button.
> fix: use dropdown instead of menu for table block entity "more" actions

- apps/web/app/home/page.tsx
- apps/web/core/environment/environment.ts
- apps/web/core/hooks/use-access-control.ts
This PR removes using the subgraphs for role information in favor of using the substream which now has correct role information.
> feat: use substreams for roles

- packages/substream/package.json
- packages/substream/sink/entries/map-entries.ts
- packages/substream/sink/proposals/map-proposals.ts
- packages/substream/sink/sql/init-public.sql
- packages/substream/sink/utils/ipfs.ts
- packages/substream/sink/zapatos/schema.d.ts
- packages/substream/sink/zod.ts
For now the json indexing is disabled since it takes up _a lot_ of space. This is useful for debugging or inspecting proposal data coming from IPFS
> feat: index proposal uris and json

- apps/web/partials/editor/editor.tsx
- apps/web/partials/editor/trailing-node.tsx
- apps/web/partials/entity-page/entity-page-cover.tsx
- apps/web/styles/styles.css
This PR adds a trailing node to the editor when the last node isn't a paragraph, making it possible to still add content where the existing gap cursor cannot reach.
> fix: tiptap issues

- apps/web/core/io/subgraph/fetch-table-row-entities.ts
This PR adds a default sort to table blocks.
> fix: table sorting

- apps/web/app/api/client.ts
- apps/web/core/environment/environment.ts
- apps/web/core/hooks/use-aragon.tsx
- apps/web/core/io/subgraph/fragments.ts
- apps/web/core/presence/entity-presence-client.ts
- apps/web/core/wallet/wallet.tsx
We wanted to use Effect for this but for some reason their provider wasn't able to read our variables from the process context. We might have to write our own to work with next or something.
> fix: typed-ish environment vars

- packages/api/package.json
- packages/api/src/config.ts
- packages/api/src/db.ts
- packages/api/src/get-block-meta.ts
- packages/api/src/meta-plugin.ts
- packages/api/src/server.ts
- packages/api/src/status-plugin.ts
- Add "subgraphs" parameter to indexStatuses
- Add "_meta" field handler (via rpc request for now)
> add _meta and fix indexStatuses

- apps/web/core/merged/triples.tsx
- apps/web/core/state/actions-store/actions-store.tsx
- apps/web/core/state/entity-page-store/entity-store.tsx
- apps/web/core/utils/triple/triple.ts
- apps/web/partials/editor/editor.tsx
This includes merging with an initial set of triples and applying a selector to the triples
> feat: add better mechanism for getting triples from local store

- apps/web/partials/entity-page/editable-entity-page.tsx
- packages/ids/system-ids.ts
This PR adds support for specifying a template for types.
> feat: entity templates

- apps/web/app/space/(entity)/[id]/[entityId]/default-entity-page.tsx
- apps/web/app/space/(entity)/[id]/[entityId]/profile-entity-server-container.tsx
- apps/web/app/space/[id]/page.tsx
- apps/web/core/state/editor-store.tsx
- apps/web/partials/editor/editor.tsx
- apps/web/partials/editor/server-content.tsx
- apps/web/partials/entity-page/entity-page-referenced-by-server-container.tsx
- apps/web/partials/entity-page/entity-page-referenced-by.tsx
This PR adds alternate initial rendering for block content.
> feat: blocks ssr

- apps/web/partials/blocks/table/table-block-table.tsx
- apps/web/styles/tiptap.css
This PR adds a description to gallery views and adds mobile/tablet optimizations for list and gallery views.
> feat: refine data blocks

- apps/web/atoms/index.ts
- apps/web/core/hooks/use-search.ts
- apps/web/core/io/subgraph/fetch-results.ts
- apps/web/core/io/subgraph/fragments.ts
- apps/web/core/io/subgraph/index.ts
- apps/web/core/io/subgraph/network-local-mapping.ts
- apps/web/core/io/subgraph/subgraph-interface.ts
- apps/web/core/merged/merged.ts
- apps/web/core/types.ts
- apps/web/design-system/select-entity.tsx
- apps/web/design-system/toggle.tsx
- apps/web/partials/entity-page/editable-entity-page.tsx
- apps/web/styles/styles.css
- apps/web/tailwind.config.js
- packages/substream/sink/events/proposals-created/get-proposal-from-ipfs.ts
This PR adds the new entity selection experience.
> feat: select entity

- apps/web/core/events/edit-events.ts
- apps/web/core/hooks/use-on-click-outside.ts
- apps/web/design-system/icons/collection.tsx
- apps/web/design-system/select-entity-dialog.tsx
- apps/web/design-system/select-entity.tsx
- apps/web/partials/entity-page/editable-entity-page.tsx
- apps/web/partials/entity-page/triple-type-dropdown.tsx
- apps/web/styles/styles.css
This PR adds support for collection attributes.
> feat: collection attributes

- apps/web/design-system/menu.tsx
- apps/web/partials/blocks/table/table-block-context-menu.tsx
- apps/web/partials/create-space/create-space-dropdown.tsx
This PR fixes the popover menu spacing.
> fix: menus

- apps/web/core/state/table-block-store.tsx
- apps/web/design-system/menu.tsx
- apps/web/package.json
- apps/web/partials/blocks/table/data-block-source-menu.tsx
- apps/web/partials/blocks/table/data-block-view-menu.tsx
- apps/web/partials/blocks/table/table-block-context-menu.tsx
- apps/web/partials/blocks/table/table-block-editable-title.tsx
- apps/web/partials/blocks/table/table-block-table.tsx
- apps/web/partials/blocks/table/table-block.tsx
- pnpm-lock.yaml
This PR adds the new data source menu.
> feat: data source menu

- apps/web/core/hooks/use-spaces-query.ts
- apps/web/core/io/schema.ts
- apps/web/core/io/subgraph/fragments.ts
- apps/web/partials/blocks/table/data-block-source-menu.tsx
This PR abstracts a new `useSpacesQuery` for space metadata.
> fix: data source query

- apps/web/core/blocks-sdk/table.test.ts
- apps/web/core/blocks-sdk/table.ts
- apps/web/core/database/entities.ts
- apps/web/core/io/subgraph/fetch-entities.ts
- apps/web/core/io/subgraph/fetch-triples.ts
- apps/web/core/state/table-block-store.tsx
- apps/web/partials/blocks/table/table-block-editable-filters.tsx
- apps/web/partials/entity-page/entity-page-utils.tsx
This PR adds functionality for filtering a data set by entity types
> feat: data block filter with types

- apps/web/core/io/dto/ops.ts
- apps/web/core/io/dto/proposals.ts
- apps/web/core/io/schema.ts
- apps/web/core/io/subgraph/fetch-proposal.ts
- apps/web/core/io/subgraph/fragments.ts
- apps/web/core/utils/change/change.ts
- apps/web/core/utils/change/from-proposed-version.ts
- apps/web/core/utils/change/get-triple-change.ts
- apps/web/core/utils/change/types.ts
- apps/web/partials/active-proposal/content-proposal.tsx
- apps/web/partials/active-proposal/get-active-proposal-diff.ts
- apps/web/partials/active-proposal/get-ended-proposal-diff.ts
- apps/web/partials/diff/changed-entity.tsx
- apps/web/partials/governance/governance-proposals-list.tsx
- apps/web/partials/review/review.tsx
- packages/substream/index.ts
- packages/substream/sink/bootstrap-root.ts
- packages/substream/sink/db/constants.ts
- packages/substream/sink/db/ops.ts
- packages/substream/sink/db/triples.ts
- packages/substream/sink/events/get-triple-from-op.ts
- packages/substream/sink/events/initial-proposal-created/handler.ts
- packages/substream/sink/events/proposal-processed/populate-triples.ts
- packages/substream/sink/events/proposals-created/handler.ts
- packages/substream/sink/events/proposals-created/map-proposals.ts
- packages/substream/sink/sql/init-public.sql
- packages/substream/sink/zapatos/schema.d.ts
This PR adds functionality for writing ops to the db when users publish edits.
> feat: substream ops

- apps/web/core/database/relations.ts
- apps/web/core/database/triples.tsx
This PR resolves a crash on the entities page.
> fix: entities page

- apps/web/app/api/space/deploy/deploy.ts
- apps/web/app/space/(entity)/[id]/[entityId]/default-entity-page.tsx
- apps/web/app/space/[id]/layout.tsx
- apps/web/app/tools/atoms.tsx
- apps/web/app/tools/component.tsx
- apps/web/core/io/subgraph/fetch-entities.ts
- apps/web/core/io/subgraph/fetch-tab.ts
- apps/web/core/io/subgraph/fetch-tabs.ts
- apps/web/core/utils/contracts/clone-entity.ts
- apps/web/core/utils/contracts/generate-ops-for-company.ts
- apps/web/core/utils/contracts/generate-ops-for-nonprofit.ts
- apps/web/core/utils/contracts/generate-ops-for-person.ts
- apps/web/core/utils/contracts/generate-ops-for-space-type.ts
- apps/web/partials/create-space/create-space-dialog.tsx
- apps/web/partials/editor/server-content.tsx
- apps/web/partials/tab/tab.tsx
- packages/sdk/src/system-ids/system-ids.ts
This PR implements `cloneEntity` and space templates for the new data model and fixes the space tabs.
> feat: templates

- apps/web/core/state/table-block-store.tsx
- apps/web/partials/create-space/create-space-dropdown.tsx
This PR restores the default data block placeholder images and the new entity button in the create dropdown.
> fix: QA revisions

- apps/web/design-system/menu.tsx
- apps/web/package.json
- pnpm-lock.yaml
Downgrading to framer-motion 10 fixes our animation issues everywhere
> fix: radix-integrated framer-motion animations don't work

- apps/web/design-system/table/cell.tsx
- apps/web/partials/blocks/table/table-block-table.tsx
- apps/web/partials/blocks/table/table-block.tsx
- removed border between columns
- removed shadows from tables
- gallery and list titles updates to medium title
> feat: table ui polish

- apps/web/core/database/write.ts
- apps/web/core/state/editor/editor-store.tsx
- apps/web/core/state/editor/parser.ts
- apps/web/core/state/editor/text-entity.ts
- apps/web/core/state/editor/utils.ts
- apps/web/partials/editor/command-extension.ts
- apps/web/partials/editor/command-items.tsx
- apps/web/partials/editor/command-list.tsx
- apps/web/partials/editor/paragraph-node.tsx
This PR fixes a handful of editor bugs
- Creating data block no longer creates a random text block
- We now correctly set the renderable type of blocks based on the block type
- Deleted blocks in editor now calculates correctly
> fix: editor bugs

- apps/web/design-system/chip.tsx
- apps/web/design-system/icons/relation-small.tsx
- apps/web/design-system/text.tsx
- apps/web/design-system/theme/colors.ts
This PR introduces the new designs for relation chips.
> feat: relations

- packages/sdk/src/system-ids/system-ids.ts
This PR fixes the collection item relation type system ID format.
> fix: collection item system id

- apps/web/core/events/edit-events.ts
- apps/web/design-system/checkbox.tsx
- apps/web/design-system/icons/checkbox-checked.tsx
- apps/web/partials/diff/changed-entity.tsx
- apps/web/partials/entity-page/editable-entity-page.tsx
- apps/web/partials/entity-page/editable-entity-table-column-header.tsx
- apps/web/partials/entity-page/get-renderable-type-options.tsx
- apps/web/partials/entity-page/readable-entity-page.tsx
- apps/web/partials/entity-page/renderable-type-dropdown.tsx
This PR introduces the checkbox value type.
> feat: checkbox

- apps/web/core/io/subgraph/fetch-entities-batch.ts
- apps/web/core/io/subgraph/fetch-space.ts
- apps/web/core/state/editor/data-entity.ts
- apps/web/core/state/table-block-store.tsx
- apps/web/core/types.ts
- apps/web/core/utils/entity-table/entity-table.ts
- apps/web/design-system/select-entity.tsx
- apps/web/design-system/table/cell.tsx
- apps/web/partials/blocks/table/table-block-table.tsx
- apps/web/partials/editor/server-content.tsx
This PR adds support for linked and verified collection items.
> feat: collection items

- apps/web/app/home/fetch-proposed-editor.tsx
- apps/web/core/hooks/use-geo-profile.ts
- apps/web/core/hooks/use-person.ts
- apps/web/core/io/subgraph/fetch-account.ts
- apps/web/core/io/subgraph/fetch-profile-via-wallets-triple.ts
- apps/web/partials/space-page/get-first-three-editors-for-space.ts
- apps/web/partials/space-page/get-first-three-members-for-space.ts
- apps/web/partials/space-page/get-members-for-space.ts
This PR updates our profile fetching code to read from the entities with the associated account address where applicable.
> feat: render person entities in place of accounts

- apps/web/core/hooks/use-onboarding.tsx
- apps/web/core/io/subgraph/fetch-profile-via-wallets-triple.ts
This PR fixes the `fetchProfile` logic.
> fix: revise profile logic

- apps/web/design-system/select-entity.tsx
- apps/web/partials/space-page/space-notices.tsx
- apps/web/styles/styles.css
This PR fixes the project search experience of the personal space onboarding cards.
It includes a global patch for the Radix UI Popover component's width.
> fix: project search

- apps/web/core/utils/entity-table/entity-table.ts
- apps/web/design-system/icons/check-circle.tsx
- apps/web/design-system/select-entity.tsx
- apps/web/design-system/toggle.tsx
- apps/web/design-system/tooltip.tsx
- apps/web/partials/blocks/table/table-block-table.tsx
- packages/sdk/src/core/scheme.ts
- packages/sdk/src/types.ts
This PR introduces the new select entity and verification design.
> feat: new select entity

- apps/web/core/state/editor/block-types.ts
- apps/web/core/state/editor/editor-store.tsx
- apps/web/core/utils/utils.ts
- apps/web/partials/editor/command-items.tsx
This PR restores support for image blocks.
> feat: image blocks

- apps/web/core/state/editor/editor-store.tsx
Previously if the editor was transitioning to an empty state we would bail out of the logic for creating/deleting relations for any new blocks. This meant that if we could never delete the last relation in the editor.
> feat: run relations modification logic for all blocks in editor

- apps/web/core/database/Triple.ts
- apps/web/core/database/types.ts
- apps/web/core/database/write.ts
- apps/web/core/events/edit-events.ts
- apps/web/core/types.ts
- apps/web/core/utils/to-renderables.ts
- apps/web/core/value-types.ts
- apps/web/partials/entity-page/editable-entity-page.tsx
- apps/web/partials/entity-page/get-renderable-type-options.tsx
- apps/web/partials/navbar/navbar.tsx
This PR restores image attribute functionality and fixes several bugs with renderables.
> feat: image attributes

- apps/web/core/database/write.ts
- apps/web/partials/review/review.tsx
Hiding this UI for now until we can implement it.
> feat: hide granular deletes

- apps/web/app/space/[id]/governance/page.tsx
Disabling the filter until we can implement it
> fix: disable proposals filter

- apps/web/core/hooks/use-local-changes.ts
- apps/web/core/utils/change/change.ts
- apps/web/core/utils/change/get-relation-change.ts
- apps/web/core/utils/change/types.ts
- apps/web/partials/review/review.tsx
- empty space as initial selected space
- diffs as a result of relations appearing in the wrong space
> fix: invalid states in review screen

- apps/web/core/hooks/use-publish.ts
- apps/web/core/io/ipfs-client.ts
This PR adds support for retries from the client for IPFS uploads and publish transactions.
> feat: client side retries

- apps/web/core/utils/change/change.ts
- apps/web/partials/review/flow-bar.tsx
Reverts geobrowser/geogenesis#1027
> Revert "feat: diff change counts in real time"

- apps/web/design-system/dialog.tsx
Framer motion upgrades broke dialog rendering. Removing motion for now.
> fix: dialog rendering

- apps/web/partials/blocks/table/table-block-edit-properties-panel.tsx
- apps/web/partials/blocks/table/table-block-table.tsx
This PR adds functionality to be able to add arbitrary properties to be rendered in the list and gallery views.
> feat: arbitrary property rendering in list/gallery views

- apps/web/app/api/space/deploy/deploy.ts
Instead retry the entire deployment flow instead of the granular dao contracts deployment.
> fix: don't retry on contract deploy

- apps/web/app/home/accept-or-reject-editor.tsx
- apps/web/core/hooks/use-access-control.ts
- apps/web/core/hooks/use-add-editor.ts
- apps/web/core/hooks/use-add-member.ts
- apps/web/core/hooks/use-deploy-space.ts
- apps/web/core/hooks/use-onboard-guard.ts
- apps/web/core/hooks/use-onboarding.tsx
- apps/web/core/hooks/use-publish.ts
- apps/web/core/hooks/use-remove-editor.ts
- apps/web/core/hooks/use-remove-member.ts
- apps/web/core/hooks/use-request-to-be-editor.ts
- apps/web/core/hooks/use-request-to-be-member.ts
- apps/web/core/hooks/use-smart-account-transaction.ts
- apps/web/core/hooks/use-smart-account.ts
- apps/web/core/wallet/wallet.tsx
- apps/web/partials/active-proposal/accept-or-reject.tsx
- apps/web/partials/create-space/create-space-dialog.tsx
- apps/web/partials/import/publish.tsx
- apps/web/partials/navbar/navbar-actions.tsx
- apps/web/partials/onboarding/dialog.tsx
This PR fixes a flash of incorrect UI when loading a user's smart account and Geo profile.
> fix: initial user loading state in navbar

- apps/web/partials/entity-page/editable-entity-page.tsx
- apps/web/partials/space-page/space-members-manage-dialog.tsx
- Manage editors/members dialog not showing
- Updating "Add Attribute" to "Add Property"
> feat: misc onboarding feedback

- apps/web/package.json
- pnpm-lock.yaml
This fixes error with parsing optional space ids from the graph scheme
> fix: upgrade to latest grc-20

- apps/web/app/export-wallet/export-wallet.tsx
- apps/web/app/export-wallet/page.tsx
Added the page `/export-wallet`
> feat: add export wallet page

- apps/web/app/home/page.tsx
minor change I found by accident
> chore: remove unnecessary React import

- apps/web/core/blocks/data/data-selectors.ts
- apps/web/core/blocks/data/filters.ts
- apps/web/core/blocks/data/queries.ts
- apps/web/core/blocks/data/use-filters.ts
- apps/web/core/blocks/data/use-mapping.ts
- apps/web/core/database/entities.ts
- apps/web/core/database/relations.ts
- apps/web/core/database/results.ts
- apps/web/core/database/write.ts
- apps/web/core/hooks/use-create-entity-from-type.ts
- apps/web/core/hooks/use-renderables.ts
- apps/web/core/io/fetch-columns.ts
- apps/web/core/state/entity-page-store/entity-store.tsx
- apps/web/core/sync/orm.ts
- apps/web/core/sync/use-store.tsx
- apps/web/core/sync/use-sync-engine.tsx
- apps/web/core/utils/change/change.ts
- apps/web/partials/blocks/table/table-block-edit-properties-panel.tsx
- apps/web/partials/blocks/table/table-block-list-item.tsx
This reverts commit 760b2e3850e2a331296e6c8b9fbe7d9e2a39d623.
> Revert "feat: replace entity merging async with sync engine fns (#1134)"

- apps/web/core/blocks/data/use-collection.ts
There's currently no way to guarantee collection item ordering when using id: { in: ... } with the sync query engine. For now we can manually order based on the results of the items in the collection
> fix: guarantee collection item ordering

- apps/web/core/utils/utils.test.ts
- apps/web/core/utils/utils.ts
- apps/web/design-system/editable-fields/date-field.tsx
- apps/web/partials/diff/changed-entity.tsx
- apps/web/partials/entity-page/date-format-dropdown.tsx
- apps/web/partials/entity-page/editable-entity-page.tsx
Implement date ranges.
Value for range is two ISO strings separated by `/`
---
---
> feat: implement date ranges

- apps/web/core/blocks/data/use-view.ts
- apps/web/design-system/editable-fields/editable-fields.tsx
- apps/web/partials/blocks/table/table-block-list-item.tsx
- apps/web/partials/blocks/table/table-block-table.tsx
- apps/web/partials/blocks/table/table-block.tsx
Fix missing data block placeholders and clipped list images
> fix: data block placeholders

- apps/web/design-system/editable-fields/date-field.tsx
Ticket: https://linear.app/geobrowser/issue/GEO-1442/date-improvement
https://github.com/user-attachments/assets/6e57587d-92d2-43ab-b3af-2bad25c86164
[queueMicrotask](https://developer.mozilla.org/en-US/docs/Web/API/Window/queueMicrotask) was used to wait until state changes are applied.
> feat: autofocus date input fields

- apps/web/core/state/editor/use-editor.tsx
- apps/web/partials/entity-page/readable-entity-page.tsx
Fix reordering bug that would happen on new and existing editor content
> Fix: editor reordering

- apps/web/design-system/chip.tsx
- apps/web/partials/blocks/table/collection-metadata.tsx
- apps/web/partials/blocks/table/table-block-bulleted-list-item.tsx
- apps/web/partials/blocks/table/table-block-gallery-item.tsx
- apps/web/partials/blocks/table/table-block-list-item.tsx
- apps/web/partials/blocks/table/table-block-property-field.tsx
- apps/web/partials/blocks/table/table-block-table.tsx
- apps/web/partials/entities-page/entity-table-cell.tsx
- apps/web/partials/entity-page/editable-entity-page.tsx
- apps/web/partials/entity-page/editable-entity-table-cell.tsx
- apps/web/partials/entity-page/readable-entity-page.tsx
This PR implements linking and verifying for relation chips.
> feat: relation actions

- apps/web/core/sync/engine.ts
- apps/web/package.json
- pnpm-lock.yaml
This PR updates our sync requests to be batched instead of one-off.
> feat: batch syncing requests

- apps/web/core/state/entity-page-store/entity-store.tsx
- apps/web/core/sync/use-store.tsx
- apps/web/partials/blocks/table/table-block-gallery-item.tsx
- apps/web/partials/blocks/table/table-block-list-item.tsx
- apps/web/partials/blocks/table/table-block-property-field.tsx
- apps/web/partials/blocks/table/table-block.tsx
- apps/web/partials/entities-page/entity-table-cell.tsx
- apps/web/partials/entity-page/editable-entity-cover-avatar-header.tsx
- apps/web/partials/entity-page/editable-entity-page.tsx
- apps/web/partials/entity-page/editable-entity-table-cell.tsx
- apps/web/partials/entity-page/readable-entity-page.tsx
This PR introduces new singular `useRelation` and `useValue` hooks/functions.
> feat: store hooks
