geobrowser/geogenesis

apps/web/modules/services/network.ts
apps/web/modules/state/triple-store.tsx
apps/web/pages/space/[id]/[entityId].tsx

This lets us reuse Network instances since not every usage of Network methods requires cancellation capability.

Caller should pass in abort controller

---

apps/web/modules/design-system/button.tsx

A previous change used the incorrect color styles for the `SmallButton` hover and focus states. We should write tests for our DS components at some point.

Fix small button hover/focus styles

---

apps/web/modules/components/entity-table/entity-table-container.tsx
apps/web/modules/components/triples.tsx
apps/web/modules/services/network.ts
apps/web/modules/triple/entity-table-store-provider.tsx
apps/web/modules/triple/entity-table-store.tsx
apps/web/modules/triple/triple-store.tsx
apps/web/modules/triple/use-entity-tables.tsx
apps/web/modules/triple/use-triples.tsx
apps/web/pages/space/[id]/entities.tsx

When filtering for 'asdfasdf' or other gibberish, both entity table and triples table would display initial rows fetched during SSR.
Rather than using filter state to determine whether or not to show SSR rows, I instead used a hydrated$ flag to mark when client side should be responsible for displaying data. 
This feels closer to the intent of our table filtering logic and less prone to bugs, especially as we begin to add table editing functionality.
Also used this PR as an opportunity to pass in the new abortController to fetchEntityTableData to prevent race conditions.

Resolve filtering for 'asdfasdf' bug showing initial state for entity and triples table

---

apps/web/modules/triple/triple.test.ts
apps/web/modules/triple/triple.ts

We are keeping local IDs static when creating and editing new local triples in order to handle diffing and change count more gracefully. This caused a bug where each newly created triple had the same triple ID.
We now create a unique value ID on triple creation so the triple ID is unique across local triples.

Fix: Create multiple triples simultaneously

---

apps/web/modules/components/entity/edit-events.ts

Previously we were updating the last triple in the entity attribute group. Instead we should be creating a new entity and deleting the last one so we can correctly squash the actions before publish.

Fix: UX for deleting the last entity relation in an attribute group

---

apps/web/modules/action/action.test.ts
apps/web/modules/action/action.ts
apps/web/modules/action/actions-store.tsx
apps/web/modules/action/use-actions-store.tsx
apps/web/modules/components/entity-table/editable-entity-table-cell.tsx
apps/web/modules/components/entity/edit-events.ts
apps/web/modules/components/entity/editable-entity-page.tsx
apps/web/modules/components/flow-bar.tsx
apps/web/modules/types.ts
apps/web/pages/_app.tsx

Instead of blowing away local actions we can persist them to keep a more optimistic experience, especially since dealing with blockchain transaction and subgraph indexing time can be slow.
We added a `hasBeenPublished` flag to local actions to know whether there are new actions since last publish and to show the FlowBar.

Keep local actions after publish

---

apps/web/modules/services/network.ts

I'll add tests and improve the network types as part of [this PR](https://github.com/geobrowser/geogenesis/pull/163) since I'm touching a bit of the network file already. Just wanna get this fix out ASAP.

fix: Filter triples from subgraph on client that have an empty attribute or empty entity value

---

apps/web/modules/components/space/space-header.tsx

`next/image` doesn't use `width` or `height` when `layout="fill"`

fix: next/image component width/height usage

---

apps/web/integration/pages/space/[id]/[entityId].test.tsx
apps/web/modules/components/entity/editable-entity-page.tsx
apps/web/modules/entity/entity.test.ts
apps/web/modules/entity/entity.ts

There was a bug where we were using the incorrect description filter on entity triples. It's now updated to use a global `Entity.descriptionTriple` helper.

fix: Description editing bug is using incorrect description filter

---

apps/web/modules/components/entity/edit-events.ts
apps/web/modules/entity/autocomplete.tsx
apps/web/modules/entity/entity-store.tsx
apps/web/modules/entity/entity.test.ts
apps/web/modules/entity/entity.ts
apps/web/modules/services/network.ts
apps/web/modules/triple/triple-store.tsx
apps/web/modules/triple/triple.ts
apps/web/modules/types.ts

As part of the editing flow users may create entities locally that they want to reference from other entities. Right now they need to publish these new entities before they are able to reference them.
This PR adds the ability to search locally created and edited entities with the search results from the network when searching for entities.

feat: search locally created entities

---

apps/web/modules/components/entity-table/entity-input.tsx
apps/web/modules/components/entity-table/entity-table-container.tsx
apps/web/modules/components/entity-table/entity-table.tsx
apps/web/modules/components/filter/type-dialog.tsx
apps/web/modules/components/table/styles.tsx
apps/web/modules/components/triple-table.tsx
apps/web/pages/_app.tsx
apps/web/react-table.d.ts

Right now if a table if wider than 1200px it will squish the columns to be as small as possible to accomodate the fixed width. We're now setting a minimum width for columns so they are more readable, and now the table will be horizontally scrollable if it expands beyond 1200px.

feat: horizontal scrollable tables

---

apps/web/modules/components/entity-table/entity-table.tsx
apps/web/modules/entity/entity-store/entity-store.tsx
apps/web/modules/entity/entity-table-store/entity-table-store.tsx
apps/web/modules/entity/index.ts
apps/web/modules/services/network.ts
apps/web/pages/space/[id].tsx

We are updating the entire table every time there is an edit to an entity in the table. This is pretty slow on its own, but having 100 rows in the table exacerbates it. Additionally, creating 200+ styled-components on every table rerender is expensive. It may make sense for us to move to a static styling mechanism instead of a runtime one at some point. For now the 50 row limit should be good enough.

fix: change entities table to 50 items

---

packages/ids/system-ids.ts

VALUE_TYPE, RELATION, and TEXT should mirror existing SF space entity IDs

Update system ids for root bootstrap file

---

apps/web/modules/components/entity/edit-events.ts
apps/web/modules/entity/entity-store/entity-store.tsx
apps/web/modules/entity/entity.ts
apps/web/modules/triple/triple-store.tsx
apps/web/modules/triple/triple.test.ts
apps/web/modules/triple/triple.ts

We are now updating the `entityName`, `attributeName` and `value.name` of all triples if there associated entity's name has changed.

fix: merge local name change actions with triples

---

apps/web/modules/services/network.ts
apps/web/modules/types.ts
apps/web/pages/space/[id].tsx
packages/ids/system-ids.ts

Works on reload too and other type selections. Not included in bootstrap file since this is a temp thing. Only works in prod.

Default type for entities

---

apps/web/modules/entity/entity.test.ts
apps/web/modules/entity/entity.ts

This was due to us not adding the `nameTripleSpace` to local entities when mapping triples to entities.

fix: cannot navigate to local entity from global search

---

apps/web/modules/components/flow-bar.tsx
apps/web/modules/design-system/icons/retry-small.tsx
apps/web/modules/services/network.ts
apps/web/modules/types.ts

Previously there was no step in the publish toast telling the user to sign the outgoing publish transaction in their wallet. Additionally, sometimes the notification for signing the notification would never appear in the wallet, leaving users in a purgatory state where they couldn't sign the transaction and couldn't retry without refreshing the page and losing their work.
This feature handles now enables users to retry the transaction prompt. In the future we will investigate the root cause for missing tx notification and also store user changes in persistent storage.

feat: add additional toast step for signing tx during publish

---

apps/web/modules/components/entity-table/entity-table.tsx
apps/web/modules/services/network.ts

For some reason the table value for the name field is stale when changing the selectedType in edit mode. When debugging it looks like the cell has the correct data, but the value of the name is the value of the last cell in the previous selectedType. For now we can use a key to force the cell to re-mount when the selectedType and name changes.

fix: stale name cell

---

apps/web/README.md
apps/web/modules/action/action.ts
apps/web/modules/components/entity-table/entity-table-container.tsx
apps/web/modules/components/entity/editable-entity-page.tsx
apps/web/modules/components/entity/presence/entity-others-toast.tsx
apps/web/modules/components/entity/presence/entity-presence-provider.tsx

Previously we were showing all users who were in edit mode on an editable entity.
Now we only show users who have made changes to this entity and are currently viewing the entity. Also, if you are the only connected tab who had made changes to an entity we will not show the toast

feat: conditional user presence

---

apps/web/modules/wallet.tsx

Previously we were exposing mumbai to users in production. Now users can only connect to polygon in production, and in development both mumbai and local chains are available.

feat: dev chains should only be available in development env

---

apps/web/modules/components/entity/autocomplete/results-list.tsx

fix: checkmark for already selected entity in search should be

---

apps/web/modules/components/entity-table/entity-table-cell.tsx

We should be fixing this at compile-time with the `noUncheckedIndexedAccess` flag in TypeScript, but right now the DX for that flag is terrible since it does not correctly narrow the type after you check it.

fix: triples array on cell may be empty, resulting in runtime error

---

apps/web/modules/avatar.tsx
apps/web/modules/components/entity-page/entity-page-metadata-header.tsx
apps/web/modules/components/entity/presence/entity-others-toast.tsx
apps/web/modules/components/history/history-item.tsx
apps/web/modules/design-system/avatar-group.tsx
apps/web/modules/entity/entity.ts
apps/web/modules/onboarding/dialog.tsx
apps/web/modules/services/io/queries.ts
apps/web/modules/services/network-local-mapping.ts
apps/web/modules/services/network.ts
apps/web/modules/types.ts
packages/ids/system-ids.ts
packages/subgraph/src/actions.ts

Right now there is no wallet -> profile mapping in the subgraph until we added permissionless spaces and profiles. We can create an ad-hoc profile system using GeoEntities and associated them with a Wallet entity.
This PR sets up infrastructure for querying a Profile GeoEntity based on the wallet address in a version's createdBy field. We then add the profile information to the version to populate the name and avatar.
---
**Demo here**
https://share.cleanshot.com/pn6v2wXS

feat: merge profile with versions on the server when fetching proposed versions

---

packages/contracts/.openzeppelin/polygon.json
packages/contracts/scripts/deploy-permissioned-space-registry.ts
packages/ids/system-ids.ts

We store the address of the beacon contract used to proxy implementations to our contracts. The value was using the incorrect contract address previously.

fix: update to correct beacon address

---

apps/web/modules/components/filter/type-dialog.tsx

This was added in a previous type dialog design. Since the design changed we no longer need it, but it sometimes will jankily animate in.

fix: remove layout animation on type dialog input

---

apps/web/modules/persistence.tsx

This PR filters out published actions before being saved to localStorage.

fix: only persist unpublished actions

---

apps/web/modules/components/entity/editable-entity-page.tsx
apps/web/modules/components/entity/editable-fields.tsx
apps/web/modules/components/entity/entity-page-content-container.tsx

We were not correctly setting the dynamic height of the expandable text area previously. We also were setting a fixed width for the entity page content container which did not scale responsively for smaller widths.

fix: fix editable entity name truncating and entity page responsiveness

---

apps/web/modules/action/action.ts
apps/web/modules/action/actions-store.ts
apps/web/modules/components/flow-bar.tsx
apps/web/modules/entity/entity-store/entity-store.ts
apps/web/modules/persistence.tsx
docs/pages.md

This PR handles some edge-cases when deleting content from the text editor on an Entity Page
- If we delete a block from the editor, it should also delete the block entity for that block. Right now we don't have transclusion, so we can safely delete the entity without any dangerous side-effects for other pages.
- If we delete the _last_ block in the text editor, we delete the `block ids` triple, too.

feat: deleting a block from the editor should delete the block entity

---

apps/web/modules/services/io/queries.ts
apps/web/modules/services/network.ts

For now we don't want to clutter entity search with all the block entities within Geo. Eventually, once we have transclusion and other block-based reference or querying features we may want to index entities or handle network filtering a different way. For now this works.
---
**Demo here**
https://share.cleanshot.com/LdLjRgy9

feat: filter blocks from entity search

---

apps/web/modules/action/actions-store-provider.tsx
apps/web/modules/components/entity-table/entity-table.tsx
apps/web/modules/components/flow-bar.test.tsx
apps/web/modules/components/flow-bar.tsx
apps/web/modules/io/data-source/local.tsx
apps/web/modules/io/mocks/mock-network.ts
apps/web/modules/stores/use-editable.ts

The local store doesn't account for deletions as changes since it only tracks the current state of triples. If a triple was deleted this won't be tracked.

fix: flow bar should use actions store instead of local store

---

apps/web/modules/components/entity/editable-entity-header.tsx
apps/web/modules/spaces/fetch-types.ts
apps/web/pages/space/[id].tsx
apps/web/pages/space/[id]/[entityId].tsx
apps/web/pages/space/[id]/create-entity.tsx

We previously refactored the heading editor to be lifted above the editable/readabable pages. We forgot to do the same thing for the `create-entity` page. This made it so you couldn't add text editor content when creating a new entity.
This PR also abstracts type fetching to the `spaces` module so `space/create-entity`, `/space/[id]` and `/space/[id]/[entityId]` can all consume the same functionality.

fix: add editor heading back to create-entity

---

apps/web/modules/components/editor/blocks/table/table-block-store.tsx
apps/web/modules/components/editor/blocks/table/table-block.tsx
apps/web/modules/components/entity/entity-page-cover.tsx
apps/web/modules/design-system/chip.tsx

This PR implements the following fixes:
- table names no longer revert on blur
- pages have reduced space below covers when no avatar is present
- chips with long content now wrap to multiple lines

fix: ux issues

---

apps/web/modules/components/editor/blocks/table/table.tsx
apps/web/modules/components/entity-table/entity-table.tsx

This PR resolves an error caused by the creation of new entities that match the filter of a client-side rendered table block.

fix: table crash

---

.github/workflows/test.yml
apps/web/modules/components/editor/blocks/table/table-block-store.tsx
apps/web/modules/components/editor/blocks/table/table-block.tsx

Since legendstate computed evaluates asynchronously, we were initially setting the result of the table construction as `false` when the `rows` computed executed. We _then_ started evaluating the result of network data, triggering the loading state back to `true`.
We now do all row and column evaluation within the networkData computed callback so table construction for rows and columns happens synchronously, resulting in the correct loading state.

fix: incorrect initial table loading state

---

apps/web/modules/components/editor/command-items.tsx

This PR automatically populates the initial table block name.

fix: table block name sync on blur

---

apps/web/integration/pages/space/[id]/[entityId].test.tsx
apps/web/modules/components/entity-page/entity-page-context-menu.tsx
apps/web/modules/components/entity-page/entity-page-delete-entity-modal.tsx
apps/web/modules/components/entity-page/entity-page-metadata-header.tsx
apps/web/modules/components/entity/editable-entity-header.tsx
apps/web/modules/components/entity/editable-entity-page.tsx
apps/web/modules/design-system/chip.tsx
apps/web/modules/entity/entity-store/entity-store.ts
apps/web/modules/onboarding/dialog.tsx
apps/web/pages/space/[id]/create-entity.tsx

This PR adds a context menu for entity-wide actions on the entity page. The first two are
- Copy Id: Copies the ID of the entity
- Delete Entity: Deletes all of the entities' triples

feat: delete entity

---

.github/workflows/lint.yml
.github/workflows/test-subgraph.yml
.github/workflows/test.yml
apps/web/modules/io/data-source/network.ts

Previously we were applying client-side sorting similarly to how we do when we fetch startsWith and contains for fetchEntities. This wasn't applicable to table rows and was incorrectly re-ordering content during pagination.

fix: ordering of table rows being re-sorted incorrectly client side

---

.github/workflows/test.yml
packages/action-schema/package.json
packages/contracts/src/deploy.ts
packages/contracts/tsconfig.json

We sometimes get build errors when running tests as the ordering of the build step for the action-schema isn't deterministic.

fix: schema build ordering

---

apps/web/modules/components/history/history-item.tsx

This PR revises the history dropdown menu to replace truncation of long names with a smaller font and text wrapping.

fix: history dropdown

---

apps/web/modules/spaces/fetch-types.ts
apps/web/modules/wallet.tsx
apps/web/next.config.js
apps/web/package.json
pnpm-lock.yaml

We were previously only fetching the first 50 space types in a given space. This meant that any tables referencing the 51st+ space type would fail.
We eventually need a better model where we aren't depending on the specific number of data being fetched in order to render tables correctly. Ideally tables can fetch their selected type on their own without the caller having to pass it to it.

fix: space types being cut off

---

apps/web/README.md
apps/web/modules/config/config.ts
apps/web/modules/spaces/fetch-types.ts
apps/web/modules/wallet.tsx
apps/web/next.config.js
apps/web/package.json
pnpm-lock.yaml

WalletConnect v1 is being deprecated on June 28. This PR upgrades our wallet library, `connectkit`, to a version that supports WalletConnect v2.

feat: upgrade to walletconnect v2 compatible connectkit version

---

.github/workflows/test.yml
apps/web/modules/components/entity/editable-entity-header.tsx
apps/web/modules/components/space/space-navbar.tsx
apps/web/modules/design-system/button.tsx
apps/web/modules/utils.ts

The access control button should be visible on the space page if there is a space configuration set. Previously it was only visible on the entities/triples routes.

feat: show access control on space page

---

apps/web/modules/search/autocomplete.ts

Ideally we solve this by passing stable references into useAutocomplete, but it's okay memoizing dependencies internally if the dependencies are small. Libraries like react-query do this.

fix: infinite loop in type dropdown

---

apps/web/modules/components/entity/autocomplete/entity-created-toast.tsx

Previously it was using the page router and wasn't migrated when we introduced next 13.

fix: entity created toast should use app router

---

apps/web/partials/navbar/navbar-actions.tsx

`width` CSS property does not have ordering precedence with conflicting `width` definitions. `max-width` overwrites `width`.

fix: use max width for avatar dropdown

---

apps/web/core/merged/merged.ts

Right now we aren't applying many server filters to locally merged-in data. This PR adds filtering on local rows in a Table based on the filters applied to the table.
This might be slow if there are many filters (10+), but we can improve this over time. Ideally we come up with a system for querying remote and local data with a simplified API/query language so we don't have to re-implement filtering on the client using plain JavaScript. This idea was part of the initial thinking on the graph-client.

fix: filter local table rows by table filter

---

packages/subgraph/package.json
pnpm-lock.yaml

This PR upgrades the @graphprotocol/graph-cli from @0.33.1 to @latest -- 
I think the issue in #443 was that I was using a mismatched `pnpm` version. I started fresh with the correct version this time. Builds and passes lint locally, but unsure if will see the same error in the CI/CD.
---
This fixes the following error that occurred when running pnpm install -- " ERROR  Could not resolve feat/smaller to a commit of https://github.com/hugomrdias/concat-stream.git."
Upgrading this package to latest resolves this and allows for all packages to fully install.

fix/upgrade-@graphprotocol/graph-cli -- with matching pnpm version

---

apps/web/core/io/publish/publish.ts

Right now our publish flow can be flaky if using a mobile wallet. Our current publish flow only handled high-level errors which did not make it obvious on which step of the publish flow an error is occurring. This PR adds more granular error handling using `Effect` at every step of the publish flow that requires external IO.
We now return explicit errors for each step of the publish flow so it's obvious where an error has occurred in the process.

feat: more granular error handling for publish flow

---

apps/web/core/wallet/wallet.tsx

We have been having intermittent RPC errors on mobile wallets. This is likely because `connectkit` manually adds public and JsonRPC providers when using their default config. This PR removes the default config and manually creates configuration for wagmi. This configuration is based on `connectkit` internals, but without the additional providers.
https://github.com/family/connectkit/blob/47984040867a15ff8cbfdcdea534ad662c2d405e/packages/connectkit/src/defaultConfig.ts#L173

fix: manually configure wagmi

---

apps/web/core/providers.tsx
apps/web/core/state/status-bar-store/index.ts
apps/web/core/state/status-bar-store/status-bar-store.tsx
apps/web/partials/review/flow-bar.test.tsx
apps/web/partials/review/flow-bar.tsx
apps/web/partials/review/review.tsx

Previously the `StatusBar` only rendered in the context of the Review UI. This made sense previously as the Review feature was the only place where users could publish content.
Soon users will be able to publish content from multiple contexts, including merging entities and moving entities to other spaces. This means that we want to render the status bar in a global context so other features can take advantage of the `StatusBar` UI when handling their own publish states.
Additionally, future features like Bulk Actions will augment the flow bar in a global way. Having a single, unified way of sending messages that will augment the FlowBar will be required there as well.
This PR is the first step in abstracting in a global status bar/flow bar. Future PRs will improve the UX of changing UI …

feat: abstract status bar into global flowbar

---

apps/web/core/hooks/use-entity-page-store.ts
apps/web/core/merged/merged.test.ts
apps/web/core/merged/merged.ts
apps/web/core/state/entity-page-store/entity-store.ts
apps/web/core/types.ts
apps/web/core/utils/action/action.ts
apps/web/core/utils/value/value.ts
apps/web/partials/entity-page/attribute-configuration-menu.tsx
apps/web/partials/entity-page/editable-entity-page.tsx

This PR updates the code for reading and manipulating attribute value types in the attribute configuration menu. Previously the code to re-run and read the attribute value types for a given attribute did not execute deterministically, sometimes returning updated values and sometimes not. This is likely due to some internal memoization in the Legendstate observable code.
I've removed the observable-based logic on the store to instead run procedurally in an idiomatic, react-y way. This is now more deterministic and executes as expected. Deterministic executions has been an issue using legendstate the way we do, so this PR also serves as a PoC for moving to new patterns that don't use legendstate observables directly in application state models, eventually phasing out Legendstate entirely …

fix: janky attribute value type mutations

---

apps/web/core/state/entity-page-store/entity-store.ts
apps/web/core/utils/triple/triple.ts
apps/web/partials/blocks/table/table-block-table.tsx
apps/web/partials/entities-page/entity-table.tsx
apps/web/partials/entity-page/editable-entity-table-column-header.tsx

This can happen if we are running `fromActions` on an array of triples that has already had `fromActions` run on it.
In this case we need to replace the existing triple instead of adding a new one. Otherwise we will get duplicate triples since we've added the `createTriple` action as a triple multiple times.
For now we dedupe the entire triples array at the end of `fromActions`. If this becomes a performance problem we can instead dedupe at the `createTriple` section of the switch statement in `fromActions` instead.

fix: duplicate triples in fromActions

---

apps/web/partials/editor/editor.tsx

There was a bug where tiptap would reset after users made changes – both inter-block and adding new blocks.

fix: editor out of sync with block changes

---

apps/web/core/io/mocks/mock-network.ts
apps/web/core/migrate/migrate.tsx
apps/web/core/migrate/utils.test.ts
apps/web/core/migrate/utils.ts
apps/web/core/types.ts
apps/web/core/utils/triple/triple.ts
apps/web/package.json
pnpm-lock.yaml

Previously we would not migrate triples whose Attribute's value type changed. This PR adds functionality to allow changing Attributes. The migration service will attempt to migrate value types that are migrateable. If a value type change, or an individual triple change, is not able to be migrated it will delete the current triples.

feat: migrate value types

---

apps/web/partials/move-entity/move-entity-review.tsx

Fixes the issues reported with inconsistencies in the Move Entity flow. The redirect after a successful Move was causing issues due to the new entity not being indexed, so the user was being redirected back to the original space and entity. 
Upon a successful Move the user is now redirected to the destination space.
We can revisit the redirect destination once we have substreams in place.
Here's a screencap of the updated flow:
Here's the steps in the screencap:
- Select an entity in Personal Development
- Move it to Philosophy
- Copy the entity Id
- Upon the redirect to Philosophy (destination space) I add the `/entityId` to the route to check that the entity is in the new space
I also tested moving the same entity back and forth, to check that there aren't any inconsistencies with that …

fix: move entity

---

apps/web/app/space/[id]/[entityId]/layout.tsx
apps/web/app/space/[id]/[entityId]/page.tsx
apps/web/app/space/[id]/[entityId]/profile-entity-server-container.tsx
apps/web/app/space/[id]/entities/page.tsx
apps/web/app/space/[id]/governance/page.tsx
apps/web/app/space/[id]/page.tsx
apps/web/app/space/[id]/space-layout.tsx
apps/web/core/hooks/use-access-control.ts
apps/web/core/services/services.tsx
apps/web/partials/navbar/navbar-actions.tsx
apps/web/partials/navbar/navbar-space-metadata.tsx
apps/web/partials/navbar/navbar.tsx
apps/web/partials/space-page/get-editors-for-space.ts
packages/permissionless-subgraph/src/access-control.ts

This PR adds functionality for fetching the navbar metadata from within the navbar itself and fixes some bugs with updating the config based on the current space.
- We now fetch space metadata in the navbar instead of reading from local spaces.
- We also now recreate the config object to create a new reference. Previously downstream dependencies weren't updating with the new config state as the reference to the object was the same.

feat: permissionless navbar space metadata

---

apps/web/app/dashboard/component.tsx
apps/web/app/dashboard/page.tsx
apps/web/core/io/fetch-proposals-by-user.ts
apps/web/core/io/subgraph/fetch-interim-membership-requests.ts
apps/web/core/io/subgraph/fetch-profile-permissionless.ts
apps/web/core/io/subgraph/fetch-profile.ts
apps/web/core/io/subgraph/fetch-proposal.ts
apps/web/core/io/subgraph/fetch-proposals.ts
apps/web/core/types.ts
apps/web/partials/governance/governance-proposals-list.tsx
apps/web/partials/onboarding/dialog.tsx
apps/web/partials/space-page/get-editors-for-space.ts
apps/web/partials/space-page/space-member-row.tsx
packages/ids/system-ids.ts
packages/profile-subgraph/src/mapping.ts
packages/profile-subgraph/subgraph.yaml

This PR adds functionality to replace the existing profile mechanism with permissionlessly created profiles. If a permissionless profile for a wallet account doesn't exist it will fall back to the People space profile.

feat: use new profiles

---

apps/web/app/entry.tsx

In prep for merging into main we are disabling onboarding. Additionally, we want to disable onboarding so we can make the onboarding flow more robust, especially for rate limiting errors from alchemy.

feat: disable onboarding

---

apps/web/design-system/autocomplete/entity-text-autocomplete.tsx

This removes the click-to-reset behavior from entity text autocomplete inputs.

fix: entity text autocomplete

---

apps/web/app/space/[id]/space-layout.tsx
apps/web/app/spaces/page.tsx

This PR removes reading from space entities in the root space and instead now reads from the space configuration entity in the space itself for everything except the `useSpaces` hook.

feat: remove reading images from root spaces

---

apps/web/app/space/[id]/[entityId]/default-entity-page.tsx
apps/web/app/space/[id]/[entityId]/layout.tsx

Previously this was working, but as part of the `stream/social` work the metadata generation got moved to a separate file. Moving it back to the entity page layout fixes this.

fix: generate metadata at the entity layout

---

apps/web/app/spaces/page.tsx

Not sure why it doesn't follow the revalidate setting in the `graphql` effect.

fix: revalidate entire spaces page every minute

---

apps/web/app/home/component.tsx
apps/web/app/home/page.tsx
apps/web/core/hooks/use-geo-profile.ts
apps/web/core/io/subgraph/fetch-on-chain-profile.ts
apps/web/core/io/subgraph/fetch-profile-permissionless.ts
apps/web/core/types.ts

This PR removes stale revalidation from the For You page. This is to ensure that users always get up-to-date data. We also now do fetching of user-specific account information on the server instead of the client.

fix: no caching and additional server requests in For You

---

apps/web/app/layout.tsx
apps/web/app/not-found.tsx
apps/web/app/space/(entities)/[id]/entities/page.tsx
apps/web/app/space/(entity)/[id]/[entityId]/activity/layout.tsx
apps/web/app/space/(entity)/[id]/[entityId]/page.tsx
apps/web/app/space/(triples)/[id]/triples/page.tsx
apps/web/app/space/[id]/access-control/page.tsx
apps/web/app/space/[id]/governance/page.tsx
apps/web/app/space/[id]/layout.tsx
apps/web/app/space/[id]/page.tsx
apps/web/app/spaces/page.tsx

We need to have a good balance between a good first render time, loading and streaming data, and loading frontend assets (we have large bundles). Rendering at the edge gets us a fast render time as long as the data we're loading before streaming is fast, as we will be further from our data sources (until we get on the decentralized network).
Partial pre-rendering in Next 14 might get us the rest of the way there, with fast content pre-rendered and delivered from a CDN. Then rendering and streaming can happen in regional edge functions that are closer to our data sources.

feat(experimental): edge render all routes

---

apps/web/app/space/(entity)/[id]/[entityId]/layout.tsx
apps/web/app/space/[id]/page.tsx
apps/web/core/utils/utils.test.ts
apps/web/core/utils/utils.ts

If an entity does not have a description or cover image set we no longer fallback to the generic geobrowser metadata.

feat: don't set default opengraph description or image

---

apps/web/core/events/edit-events.ts
apps/web/partials/entity-page/editable-entity-page.tsx

This PR automatically adds the `Types` attribute as a relation field to new entities.

fix: add types to new entities

---

apps/web/app/space/(entity)/[id]/[entityId]/default-entity-page.tsx
apps/web/app/space/(entity)/[id]/[entityId]/page.tsx
apps/web/app/space/(entity)/[id]/[entityId]/profile-entity-server-container.tsx

This should correctly redirect to the personal profile space if you attempt to load a profile in your own space. This is a temporary application-level fix until we decide to move over to per-space entity data loading.

fix: redirect personal profile entities to the personal space

---

packages/substream/index.ts
packages/substream/src/populate-cache.ts
packages/substream/src/populate-from-cache.ts
packages/substream/src/populate-roles.ts
packages/substream/src/run-stream.ts
packages/substream/src/sql/initAll.sh
packages/substream/src/sql/initIndexes.sql
packages/substream/src/sql/initPublic.sql
packages/substream/src/types.ts

This PR adds the capability to read from the postgres cache tables when re-indexing from genesis. This require a cold, full-index from genesis to populate the cache tables the first time. There might be a good way to share cache to other indexers in the future.
In testing on my local machine full indexing takes anywhere from 3-10 hours depending on firehose performance. Using the cache takes ~15 minutes.

feat(substream: read from cache

---

packages/substream/package.json
packages/substream/src/populate-entries.ts
packages/substream/src/populate-roles.ts
packages/substream/src/run-stream.ts
packages/substream/src/sql/initPublic.sql
packages/substream/src/zapatos/schema.d.ts

This PR refactors the versioning model to store the full state of an entity as part of each Entity's Versions. 
Previously we stored all Actions that resulted in a specific state in each Version. To calculate the state for an Entity at a specific Version you would query the Version and re-run the Actions to build the state of the Entity. This created a few problems:
- Getting the state of a Version would mean calculating the entire state from genesis for that Entity using all of the Actions ever applied to that Entity. It wasn't ergonomic to rely on clients (or even the server) to compute the state of an Entity dynamically every time we wanted to query a historical representation of an Entity, especially if an Entity changed frequently.
- Storing all of the Actions to re-create each …

feat(substream): new entity versioning model

---

apps/web/design-system/autocomplete/entity-text-autocomplete.tsx
apps/web/partials/entity-page/editable-entity-page.tsx
apps/web/partials/entity-page/editable-entity-table-cell.tsx

This PR extends the create new entity logic of `<EntityAutocompleteDialog>` (added in #596) to apply to the `<EntityTextAutocomplete>` component as well.

fix: add relation value type

---

apps/web/core/hooks/use-access-control.ts

There is a bug in the substream for some public spaces where some roles don't get index properly. The subgraph still has correct data. Once we fully integrate the new governance contracts we can use the substream for everything again.

feat: use subgraph for public space permissions for now

---

apps/web/partials/team/find-team-member.tsx

Profile ids might grow over time with the current id system as we get more profiles. For now we ignore the lengths when checking the id in the field

fix: we shouldn't track valid entity id lengths

---

apps/web/app/space/(entity)/[id]/[entityId]/cached-entity-type.ts
apps/web/app/space/(entity)/[id]/[entityId]/cached-fetch-entity.ts
apps/web/app/space/(entity)/[id]/[entityId]/default-entity-page.tsx
apps/web/app/space/(entity)/[id]/[entityId]/layout.tsx
apps/web/app/space/(entity)/[id]/[entityId]/page.tsx
apps/web/app/space/(entity)/[id]/[entityId]/profile-entity-server-container.tsx
apps/web/app/space/(triples)/[id]/triples/page.tsx
apps/web/app/space/[id]/cached-fetch-space.ts
apps/web/app/space/[id]/layout.tsx
apps/web/app/space/[id]/page.tsx
apps/web/app/space/[id]/team/page.tsx
apps/web/core/io/fetch-onchain-profile-by-entity-id.ts
apps/web/core/io/subgraph/fetch-entities.ts
apps/web/core/io/subgraph/fetch-entity.ts
apps/web/core/io/subgraph/fetch-space.ts
apps/web/core/io/subgraph/fetch-spaces.ts
apps/web/core/io/subgraph/fetch-table-row-entities.ts
apps/web/core/merged/merged.ts
apps/web/core/state/types-store/types-store-server-container.tsx
apps/web/core/types.ts
apps/web/core/utils/entity/entity.test.ts
apps/web/core/utils/entity/entity.ts
apps/web/design-system/autocomplete/results-list.test.tsx
apps/web/design-system/autocomplete/results-list.tsx
apps/web/partials/blocks/table/table-block-context-menu.tsx
apps/web/partials/search/dialog.tsx
apps/web/partials/space-page/get-editors-for-space.ts
apps/web/partials/space-page/get-first-three-editors-for-space.ts
apps/web/partials/space-page/get-is-editor-for-space.ts
apps/web/partials/team/find-team-member.tsx

Entities can now exist in multiple spaces at once. This PR updates our navigation model to be able to handle multi-space entities. Eventually we will need a mechanism for users to be able to define which space they want an entity link to go to.

feat: handle multi-space entity navigation

---

apps/web/core/blocks-sdk/__snapshots__/table.test.ts.snap
apps/web/core/blocks-sdk/table.test.ts
apps/web/core/blocks-sdk/table.ts
apps/web/core/io/subgraph/fetch-table-row-entities.ts

Entities now store _all_ triples that have ever been applied to any entity, so we need to make sure we're only filtering on active triples

fix: apply isStale filter to table filter queries

---

apps/web/core/io/publish/publish.ts
apps/web/partials/onboarding/create-profile-dialog.tsx

We have a separate flow for creating a profile if a wallet has an on-chain profile but not a Geo entity profile. We did not update this flow when updating to adding the space type to the entity itself instead of creating a separate space configuration entity

fix: add space type to created profile

---

apps/web/app/api/company/deploy/make-company-effect.ts
apps/web/app/api/contracts/deploy/make-deploy-effect.ts
apps/web/app/api/nonprofit/deploy/make-nonprofit-effect.ts
apps/web/app/api/person/deploy/make-person-effect.ts
apps/web/core/io/publish/contracts.ts

We might be running into RPC rate limits in our node providers. We currently only have exponential backoff when making contract calls. This PR adds jittering to the calls and lowers the base value for the backoff.
This PR also adds some very basic client-side logging to debug any errors we get back from the server during onboarding to make sure errors in both environments align.

fix: jittered backoff in onboarding

---

apps/web/app/home/component.tsx
apps/web/partials/governance/governance-proposals-list.tsx
apps/web/partials/space-page/space-editors-chip.tsx
apps/web/partials/space-page/space-member-row.tsx
apps/web/partials/space-page/space-members-chip.tsx

Currently in some places we use an editor/profile's id as the seed for the avatar's default image and some places we use the address. This PR aligns all the usage to use the address as there may be instances where a user does not have a Geo profile.

fix: align default avatar to use address instead of id

---

apps/web/core/environment/environment.ts
packages/substream/sink/entries/populate-entries.ts

Currently if an entity has multiple names and we delete one, we delete the name association on the entity itself. If the entity has any _additional_ names to the one that was deleted, we should instead update the entity's name to one of them.
There are probably better ways of doing this with some derived/computed columns in Postgres, but this is the simplest approach for now.

feat: substream should handle many names for an entity

---

apps/web/partials/blocks/table/table-block-context-menu.tsx

This PR ensures edit columns mode is exited when the table block context menu is closed.

fix: edit columns state

---

apps/web/app/api/company/deploy/make-company-effect.ts
apps/web/app/api/contracts/deploy/make-deploy-effect.ts
apps/web/app/api/contracts/deploy/route.ts
apps/web/app/api/errors.ts
apps/web/app/api/make-proposal-server.ts
apps/web/app/api/nonprofit/deploy/make-nonprofit-effect.ts
apps/web/app/api/space/deploy/make-create-entities-effect.ts
apps/web/app/api/space/deploy/make-deploy-space-effect.ts
apps/web/app/api/space/deploy/route.ts

With substreams we don't rely on spaces being added to the space registry anymore since we track all space creation being done onchain.

feat: remove adding to root space when deploying spaces

---

apps/web/app/tools/component.tsx
apps/web/app/tools/page.tsx

This PR adds a simple `/tools` page with a few new utilities for power users:
- fetch entity by id (for debugging)
- generate entity ids (for use in CSV import)
- fetch entities by space/type (for parsing what should be omitted from imports)

feat: editor tools

---

apps/web/core/environment/environment.ts

Hosted network is being sunset in a few days. This PR migrates to use the network version of our subgraphs. Once we migrate to our L3 infra these won't be used anymore, so this is temporary until then.

feat: migrate subgraphs

---

apps/web/core/migrate/utils.test.ts
apps/web/core/utils/utils.test.ts
apps/web/core/utils/utils.ts
apps/web/design-system/editable-fields/date-field.tsx

Safari did not support the previous date format we were using to generate a UTC triple from the date-field component. We now use the standard ISO-8601 format which should work across all JS runtimes.

fix: generate date triple value in safari

---

apps/web/app/space/(entity)/[id]/[entityId]/default-entity-page.tsx
apps/web/app/space/(entity)/[id]/[entityId]/profile-entity-server-container.tsx
apps/web/app/space/[id]/page.tsx
apps/web/partials/editor/editor.tsx
apps/web/partials/editor/server-content.tsx

Rendering a page during SSR with streaming RSC can block meta tag parsing on discord and twitter if there is no fallback for the streaming RSC.

fix: hydration errors in editor + SEO fix

---

apps/web/app/dao/page.tsx
apps/web/core/constants.ts
apps/web/core/io/storage/storage.ts
packages/sdk/src/proto/create-edit-proposal.ts
packages/substream/sink/bootstrap-root.ts
packages/substream/sink/db/spaces.ts
packages/substream/sink/events/editor-added/map-editors.ts
packages/substream/sink/events/get-derived-space-id-from-imported-space.ts
packages/substream/sink/events/get-derived-space-ids-from-imported-spaces.ts
packages/substream/sink/events/initial-editors-added/handler.ts
packages/substream/sink/events/initial-proposal-created/get-initial-proposals.test.ts
packages/substream/sink/events/initial-proposal-created/get-initial-proposals.ts
packages/substream/sink/events/member-added/map-members.ts
packages/substream/sink/events/onchain-profiles-registered/handler.ts
packages/substream/sink/events/proposal-processed/get-edits-proposal-from-processed-proposal.ts
packages/substream/sink/events/spaces-created/get-spaces-with-initial-proposals-processed.ts
packages/substream/sink/events/spaces-created/handler.ts
packages/substream/sink/events/spaces-created/map-spaces.ts
packages/substream/sink/events/spaces-created/parser.ts
packages/substream/sink/events/subspaces-added/map-subspaces.ts
packages/substream/sink/events/subspaces-removed/map-subspaces-to-remove.ts
packages/substream/sink/proto/decoder.ts
packages/substream/sink/run-stream.ts
packages/substream/sink/sql/init-public.sql
packages/substream/sink/utils/id.ts
packages/substream/sink/zapatos/schema.d.ts

This PR moves space ids from being contract addresses to a chain-independent uuid. For spaces that might be imported from another chain, we derive the original space id from the network and the original contract address. For new spaces we derive the id from the current network for the indexer and the contract address.

feat: index space ids as a uuid instead of contract address

---

apps/web/design-system/autocomplete/results-list.tsx
apps/web/design-system/select-entity-dialog.tsx
apps/web/design-system/select-entity.tsx
apps/web/package.json
apps/web/partials/entity-page/editable-entity-page.tsx
pnpm-lock.yaml

This PR updates the select-entity component to be consumed via multiple contexts: 1) an empty relation field 2) a non-empty relation field with a + button to trigger the select-entity experience

feat: create additional relations via + button

---

apps/web/core/database/triples.tsx
apps/web/partials/review/flow-bar.tsx

This is mostly used by things like diffs or the flowbar

feat: do not return deleted triples by default, but allow escape hatch

---

apps/web/app/home/fetch-active-proposals-in-editor-spaces.ts
apps/web/core/environment/environment.ts
packages/substream/index.ts
packages/substream/sink/cursor.ts
packages/substream/sink/db/constants.ts
packages/substream/sink/db/current-versions.ts
packages/substream/sink/db/edits.ts
packages/substream/sink/db/proposals.ts
packages/substream/sink/db/space-metadata.ts
packages/substream/sink/db/versions.ts
packages/substream/sink/events/initial-proposal-created/handler.ts
packages/substream/sink/get-stream-configuration.ts
packages/substream/sink/sql/init-indexes.sql
packages/substream/sink/write-edits/aggregate-relations.ts
packages/substream/sink/write-edits/merge-ops-with-previous-versions.ts
packages/substream/sink/write-edits/write-edits.ts

We now exit the process on timeout errors so our data service can restart the container. This is needed due to flaky timeout issues from the substream API. Restarting the container forces the connection to re-establish.

feat(sink): process exit on timeout error + performance improvements

---

apps/web/core/hooks/use-renderables.ts
apps/web/core/hooks/use-request-to-be-editor.ts
apps/web/core/hooks/use-request-to-be-member.ts
apps/web/core/hooks/use-vote.ts
apps/web/core/wallet/privy.tsx
apps/web/partials/blocks/table/table-block.tsx
apps/web/partials/editor/server-content.tsx
apps/web/partials/entities-page/entity-table-container.tsx
apps/web/partials/space-page/space-editors-join-button.tsx
apps/web/partials/triples-page/triples.tsx
packages/substream/sink/events/edits-published/aggregate-mergable-versions.test.ts
packages/substream/sink/events/edits-published/aggregate-mergable-versions.ts
packages/substream/sink/events/edits-published/handler.ts
packages/substream/sink/utils/id.ts
packages/substream/sink/write-edits/aggregate-relations.ts

Before this change we were creating merged versions in blocks that didn't contain multiple versions for the same entity. This resulted in writing duplicated relations that point to the same version of the entity both when initially writing the edits content and when handling the merge step.
Now we only create merged versions for default edits if there is at least more than one version in the same block for the entity. For imported edits we allow single versions since imports need to be aware of the full state of the import in order to process correctly.

fix: unnecessary version duplication causes duplicated relations for default edits

---

packages/substream/sink/bootstrap-root.ts

This fixes an issue where we weren't bootstrapping collection-related system entities. This resulted in triples referencing these entities not being written by the substream.

fix: collection data blocks are reverting to query after publishing

---

apps/web/core/database/entities.ts
apps/web/partials/editor/server-content.tsx
packages/substream/sink/db/edits.ts
packages/substream/sink/db/proposals.ts
packages/substream/sink/db/transaction.ts
packages/substream/sink/db/versions.ts
packages/substream/sink/events/edits-published/handler.ts
packages/substream/sink/events/initial-proposal-created/handler.ts
packages/substream/sink/events/proposals-created/handler.ts
packages/substream/sink/events/proposals-created/map-proposals.ts
packages/substream/sink/events/proposals-created/parser.ts
packages/substream/sink/proto/decoder.ts
packages/substream/sink/write-edits/aggregate-relations-v2.ts
packages/substream/sink/write-edits/aggregate-relations.ts
packages/substream/sink/write-edits/aggregate-versions.ts
packages/substream/sink/write-edits/make-version-for-stale-entity.ts
packages/substream/sink/write-edits/map-triples.ts

This PR adds functionality for creating a new version for an entity if relations from the entity are changed and there's not already a new version for that entity in the edit.
- You make a new relation from Entity A, but do not change any triples on Entity A. This does not make a new version of Entity A, so the new relation won't be associated with the latest version of Entity A in the DB
- You delete a relation from Entity A, but do not change any triples on Entity A. Same issue as 1.
This PR also fixes a bug when merging imported ops where the imported entity did not merge any pre-existing data for that entity from other spaces (or bootstrap).

fix: create new versions for entities that become stale after relation changes

---

packages/substream/sink/db/relations.ts
packages/substream/sink/sql/init-public.sql
packages/substream/sink/write-edits/relations/aggregate-relations.ts
packages/substream/sink/zapatos/schema.d.ts

We now track the space id from which relations are created. This allows us to query for entity data scoped by space for both triples and relations.

feat: space-aware relations

---

packages/substream/sink/write-edits/write-edits.ts

Previously version spaces were only deriving from triples on a version, but not relations.

fix: version spaces were not deriving from relations

---

packages/substream/sink/events/edits-published/handler.ts
packages/substream/sink/events/initial-proposal-created/handler.ts
packages/substream/sink/events/proposals-created/handler.ts
packages/substream/sink/types.ts
packages/substream/sink/write-edits/relations/aggregate-relations.ts
packages/substream/sink/write-edits/write-edits.ts

Previously we were using deleted relations from all the edits in a block.
Right now there's some duplication between the logic we're using to calculate stale entity versions and the logic for aggregating new relations. We can merge this into the same code in a future PR.

fix: use deleted relations from current edit when setting relations on new version

---

packages/substream/sink/errors.ts
packages/substream/sink/events/editor-added/handler.ts
packages/substream/sink/events/editor-added/map-editors.ts
packages/substream/sink/events/editor-removed/handler.ts
packages/substream/sink/events/editor-removed/map-removed-editors.ts
packages/substream/sink/events/edits-published/handler.ts
packages/substream/sink/events/initial-editors-added/handler.ts
packages/substream/sink/events/initial-proposal-created/handler.ts
packages/substream/sink/events/member-added/handler.ts
packages/substream/sink/events/proposals-created/handler.ts
packages/substream/sink/events/proposals-executed/handler.ts
packages/substream/sink/events/spaces-created/handler.ts
packages/substream/sink/events/subspaces-added/handler.ts
packages/substream/sink/events/subspaces-added/map-subspaces.ts
packages/substream/sink/events/subspaces-removed/handler.ts
packages/substream/sink/events/votes-cast/handler.ts
packages/substream/sink/events/write-accounts.ts
packages/substream/sink/run-stream.ts
packages/substream/sink/utils/retry-effect.ts
packages/substream/sink/write-edits/write-edits.ts
packages/substream/sink/write-edits/write-triples.ts

Most of the errors in the substream fall into a couple categories and can mostly be handled the same way
1. A space doesn't exist for a given plugin/dao address
2. Inserting into the db fails for some reason
We now bubble these errors to the caller so we can handle the same category of errors in a single place instead of ad-hoc throughout the codebase.
Next we'll need to handle gracefully failing in places where that's okay.

feat: lift error handling to handleMessage caller

---

apps/web/core/hooks/use-deploy-space.ts
apps/web/core/io/dto/entities.ts
apps/web/core/utils/contracts/generate-ops-for-space-type.ts
apps/web/partials/create-space/create-space-dialog.tsx
apps/web/partials/onboarding/dialog.tsx
packages/sdk/src/core/image.ts

We were previously using the incorrect entity id when setting the relation for an avatar or cover when creating spaces. We now return the image id from `Image.make` so consumers have easy access to the underlying image entity that was created.
Additionally, we weren't correctly handling the setting the image string for ad-hoc creation of spaces, specifically for company spaces. We now have a unified `image` state instead of an `avatar` and `cover` state.
Lastly, this fixes a bug where we weren't setting the space configuration on spaces that weren't `company`, `personal`, or `nonprofit` spaces.

fix: image uploads during space creation

---

apps/web/core/constants.ts
apps/web/core/io/schema.ts
apps/web/core/utils/change/change.ts
packages/substream/sink/events/editor-added/map-editors.ts
packages/substream/sink/events/editor-removed/handler.ts
packages/substream/sink/events/edits-published/get-edits-proposal-from-processed-proposal.ts
packages/substream/sink/events/edits-published/handler.ts
packages/substream/sink/events/get-derived-space-ids-from-imported-spaces.ts
packages/substream/sink/events/initial-editors-added/handler.ts
packages/substream/sink/events/member-added/map-members.ts
packages/substream/sink/events/member-removed/handler.ts
packages/substream/sink/events/proposals-created/handler.ts
packages/substream/sink/events/proposals-executed/handler.ts
packages/substream/sink/events/spaces-created/handler.ts
packages/substream/sink/events/subspaces-added/map-subspaces.ts
packages/substream/sink/events/subspaces-removed/handler.ts
packages/substream/sink/events/subspaces-removed/map-subspaces-to-remove.ts
packages/substream/sink/events/votes-cast/map-votes.ts
packages/substream/sink/run-stream.ts
packages/substream/sink/write-edits/merge-ops-with-previous-versions.ts
packages/substream/sink/write-edits/relations/aggregate-relations.ts
packages/substream/sink/write-edits/relations/get-deleted-relations-from-ops.ts
packages/substream/sink/write-edits/relations/get-stale-entities-from-relations.ts
packages/substream/sink/write-edits/write-edits.ts

This PR adds several performance improvements to the indexer.
- We now add concurrency to all the `Effect.all` and `Effect.forEach` calls. Previously some of them didn't specify concurrency, so Effect would execute them sequentially by default.
- We now fork some of the event handler into new fibers in `runStream`. Not all event handlers are dependent on other events in the indexer. The non-dependent events now just execute when they are able. This should help saturate CPU/IO time in the indexer.

feat(substream): saturate i/o by allowing unblocked async work to execute

---

apps/web/core/hooks/use-spaces-query.ts
apps/web/core/state/editor/sources.ts
apps/web/partials/blocks/table/data-block-source-menu.tsx

This PR fixes two bugs which were blocking changing the data block source types
- Space search was not updated to latest versioning model
- We were shadowing the source space id when creating source spaces with another space id

fix: change data source

---

apps/web/core/database/entities.ts
apps/web/partials/blocks/table/table-block-editable-filters.tsx

This is now changed via the source space selector

fix: don't need space filter in filter menu

---

apps/web/core/hooks/use-search.ts
apps/web/core/io/subgraph/fetch-result.ts
apps/web/core/io/subgraph/index.ts
apps/web/core/utils/utils.ts
apps/web/design-system/select-entity.tsx
packages/sdk/index.ts
packages/sdk/src/core/base58.ts

This PR extends the `useSearch` hook to allow searching by manually entered entity ID.

feat: search by entity id

---

apps/web/core/state/table-block-store.tsx

Previously changing any state that required async requests would send the table into a loading state when making the changes. This was janky. Now we keep previous state while computing the new state. This still isn't perfect as there might be a delay while we wait for your local state to show up in the UI, but it's better than what we had previously.

fix: keep table async data from previous state while computing new state

---

apps/web/partials/entity-page/editable-entity-page.tsx

This PR fixes a bug where we set the wrong relation data when adding the type to a new image entity.

fix: correct type when creating image entity

---

apps/web/core/io/dto/triples.ts
apps/web/core/io/schema.ts
apps/web/core/io/subgraph/fragments.ts
apps/web/core/utils/change/change.ts
packages/substream/sink/events/get-triple-from-op.test.ts
packages/substream/sink/events/get-triple-from-op.ts
packages/substream/sink/sql/init-indexes.sql
packages/substream/sink/sql/init-public.sql
packages/substream/sink/write-edits/map-triples.ts
packages/substream/sink/write-edits/merge-ops-with-previous-versions.ts
packages/substream/sink/write-edits/write-edits.ts
packages/substream/sink/zapatos/schema.d.ts

The reference data service has a versioning mechanism which enables querying any entity at any version at any point in time with a unified data model. This allows us to do time-traveling as well as compare (diff) entities over time.
In order for this to work, any data models in the data service that reference an entity must also (or instead) reference a specific version of that entity. By default the data service picks the latest version, but the model supports users being able to select versions themselves.
This PR updates the data model for triples to also reference a version for the `attribute`. Previously we were only referencing the entity for that attribute, so we could not correctly time-travel for any triples where the attribute did not previously exist.
This also updates our …

feat: triple attributes should point to a version

---

apps/web/core/utils/change/change.ts
apps/web/core/utils/change/fetch-previous-version-by-created-at.ts
apps/web/partials/active-proposal/active-proposal.tsx

This PR fixes a bug where the query for previous versions of proposed entities was fetching using the wrong time comparator.

fix: correct query for previous versions

---

apps/web/partials/diff/changed-entity.tsx

Reverted to simple square corners for now until we can correctly set top and bottom rounded borders

fix: naive fix for changed entity borders

---

apps/web/app/api/space/deploy/deploy.ts
apps/web/app/space/[id]/governance/page.tsx

This updates new space deployments for governed spaces to have 24 hour voting windows. Previously deployed governed spaces aren't being updated to 24 hours. Currently the indexer does not track voting settings for spaces, so we need to hardcode the existing space ids in order to render the correct voting window on the governance screen. In the future we'll update the indexer to track voting settings for each space.

feat: new default proposal time for new spaces

---

apps/web/app/api/bootstrap/deploy/deploy.ts
apps/web/core/io/subgraph/fetch-history-versions.ts

This might result in false positives that deploy the same space multiple times using the same ops. Instead we should retry the entire deploy flow, which we already do.

fix: don't retry DAO deployment granularly

---

apps/web/app/api/space/deploy/deploy.ts
apps/web/app/api/space/deploy/route.ts
packages/substream/sink/db/current-versions.ts
packages/substream/sink/db/versions.ts
packages/substream/sink/events/edits-published/get-edits-proposal-from-processed-proposal.ts
packages/substream/sink/events/edits-published/handler.ts
packages/substream/sink/events/proposals-created/map-proposals.ts
packages/substream/sink/sql/init-public.sql
packages/substream/sink/types.ts
packages/substream/sink/write-edits/write-edits.ts
packages/substream/sink/zapatos/schema.d.ts

This PR fixes a handful of indexing bugs related to multi-space entities and edit execution order.
- Writing version spaces incorrectly filtered which spaces a version exists in
- Any other edits executed while an edit is waiting to be executed would result in the pending edit not having all of the data from the executed edits

fix: multi-space entities + edit execution order

---

apps/web/core/utils/change/change.ts
packages/substream/sink/events/edits-published/handler.ts

This can have unintended side-effects of writing data that's already been written or affect versions that have already been frozen.

fix: only write edits in publish handler if there are fresh versions

---

packages/sdk/README.md

There's a new API service for the knowledge graph which wraps common functionality needed for programmatic writing to the knowledge graph. This PR updates the docs to point to the endpoints for these helpers.

docs: update sdk docs to point to API endpoints

---

apps/web/core/blocks/data/use-data-block.tsx
apps/web/core/state/editor/use-editor.tsx
apps/web/partials/editor/editor.tsx
apps/web/partials/editor/server-content.tsx
apps/web/partials/navbar/navbar-actions.tsx

This PR fixes a few bugs related to editor hydration. These issues mostly stem from synchronizing Geo state and Tiptap editor state. 
Previously we would store all editor block state as Geo state and let Tiptap handle it's internal state separately. There was a syncing layer between the two, but we would only sync _to_ tiptap on editor load state. This was because in older versions of Tiptap, syncing back to Tiptap for every change in Geo state would cause our custom React Tiptap nodes to re-mount, resulting in loading states for our data blocks. This seems to be resolved now in newer versions of Tiptap.
- We now sync Geo state back to Tiptap for the active editor
- We now correctly spread any Tiptap block attributes for text blocks. This manifested in bugs for our server content state …

fix: editor hydration

---

apps/web/core/state/editor/parser.ts
apps/web/core/state/editor/text-entity.ts
apps/web/partials/editor/extensions.tsx
apps/web/partials/editor/id-extension.tsx

This PR fixes a few list item bugs
- we weren't parsing the tiptap representation of list items into markdown list items correctly
- we weren't grouping list items together when they're siblings, but tiptap is. This is due to how hardbreaks interact with the editor. For now I'm disabling hard breaks.
- Tiptap was generating for some reason generates new blocks (entities) for list items

fix: list item bugs

---

apps/web/core/blocks/data/use-data-block.tsx
apps/web/core/blocks/data/use-relations-block.tsx
apps/web/core/blocks/data/use-source.ts
apps/web/partials/blocks/table/table-block-filter-creation-prompt.tsx

This PR adds some default states for new relation blocks
- Set the block name to the `from` entity
- Set the `from` entity in the relation to the current page entity
- Fixes local state to re-render when there's a new relation

feat: default states for new relation blocks

---

apps/web/app/space/(entity)/[id]/[entityId]/layout.tsx

Changes the title for relation entities to `[From entity name] -> [To entity name]`. Falls back to the entity id if it does not have a name.

feat: seo title for relations

---

apps/web/core/blocks/data/filters.ts
apps/web/core/blocks/data/source.ts
apps/web/core/blocks/data/use-filters.ts
apps/web/partials/blocks/table/table-block-filter-creation-prompt.tsx
apps/web/partials/blocks/table/table-block-table.tsx

Previously we stored the `From` relation in a special `entity` property on the block filter. We now store it as a normal `AND` filter. If we encounter a `From` filter in the app we treat it as a relations block instead of a query block.
This enables us to treat the filter storage the same for regular queries as we do relation queries. Also enables us to use `To` as a potential filter in the future and build special views for it.

feat: use normal filters for relation blocks

---

apps/web/partials/editor/server-content.tsx

If a paragraph block is empty the editor might not store the content array on the block. This can cause errors in our server content renderer. If the content does not exist we set it on the server to an empty array.

fix: set non-existent block content to empty

---

packages/substream/sink/write-edits/write-edits.ts

This PR fixes a bug where we were including deleted triples as a data source for version spaces.

fix: only include new triples in version spaces

---

apps/web/core/database/entities.ts

In a previous PR we removed it in favor of adding it at the callsite. This broke some callsites.

fix: should include defaults in schema query

---

packages/substream/sink/run-stream.ts

This PR adds a time-limit to a single block index operation to 5 minutes.

feat: limit single block read time to 5 minutes

---

apps/web/core/database/relations.ts
apps/web/core/events/edit-events.ts
apps/web/core/hooks/use-debounced-value.ts
apps/web/core/io/subgraph/fetch-history-versions.ts
apps/web/design-system/editable-fields/editable-fields.tsx
apps/web/partials/blocks/table/editable-title.tsx

We weren't updating the editable title state whenever any changes to the entity were triggered from outside of the editable title.
Since the knowledge graph is highly reactive it's common for an entity to be rendered multiple times on the same page. If this entity is changed anywhere it should be reflected reactively everywhere.

fix: reactive changes to editable title

---

apps/web/core/utils/utils.ts
apps/web/partials/entity-page/date-format-dropdown.tsx

Changed default value to `MMM d, yyyy - h:mmaaa` (e.g. _Jan 3, 2025 - 9:00am_)

feat: change default date format

---

apps/web/core/hooks/use-spaces-query.ts
apps/web/core/io/dto/search.ts
apps/web/core/io/dto/spaces.ts
apps/web/core/io/dto/subspaces.ts
apps/web/core/io/schema.ts
apps/web/core/io/subgraph/fetch-history-version.ts
apps/web/core/io/subgraph/fetch-spaces-where-editor.ts
apps/web/core/io/subgraph/fetch-spaces-where-member.ts
apps/web/core/io/subgraph/fetch-spaces.ts
apps/web/core/io/subgraph/fetch-versions-batch.ts
apps/web/core/utils/change/fetch-previous-version-by-created-at.ts
apps/web/core/utils/change/fetch-versions-by-edit-id.ts

Previously we assumed that every space had a space metadata. This isn't always true. We now also filter out invalid spaces.

fix: more fetch logs + fix space decoding errors

---

apps/web/core/io/dto/relations.ts
apps/web/core/io/schema.ts
apps/web/partials/diff/changed-entity.tsx

If the relation is new then there won't be a current version for the relation entity

fix: fetch versions by entity id decoding

---

apps/web/core/database/write.ts
apps/web/core/state/editor/use-blocks.ts
apps/web/core/state/persistence.tsx
apps/web/core/sync/engine.ts
apps/web/core/sync/store.ts
apps/web/core/sync/use-store.tsx
apps/web/partials/entity-page/editable-entity-header.tsx

This PR updates the entity sync store to use the query cache as the source of truth for view state. Previously we set tracked entities in local state. Instead we can just update the react query cache. In the future I may explore just making the entire sync store reactive rather than relying on the change events and manual tracking based on heuristics.

feat: cache as view for entity sync store

---

apps/web/core/environment/environment.ts
apps/web/core/io/v2/v2.schema.ts

We now return renderables from the API as ids and parse them on the client into specific types. Clients can now write arbitrary renderable types and as long as they can parse it in their clients, render them.

feat: dynamic renderable type

---

apps/web/partials/editor/command-list.tsx

To fix headings and lists in text editor

fix: keep editor selection by preventing blur on mousedown
